Repository p4lang/p4c, pull requests merged in 2024-05, with the labels that each got.

#4647 Introduce guard for aarch64 GCC compilation.
  BUILD.bazel
  CMakeLists.txt
  cmake/config.h.cmake
  lib/gc.cpp
Labels: core

#4649 Use check_include_file_cxx instead of check_include_file to find mm_malloc.h
  .github/workflows/ci-static-build-test.yml
  CMakeLists.txt
  lib/gc.cpp
Labels: core

#4623 Move IRUtils Literal get functions to the respective IR members. Add stringliteral get function.
  backends/p4tools/common/compiler/configuration.h
  backends/p4tools/common/compiler/convert_hs_index.cpp
  backends/p4tools/common/compiler/convert_struct_expr.cpp
  backends/p4tools/common/core/abstract_execution_state.cpp
  backends/p4tools/common/core/z3_solver.cpp
  backends/p4tools/common/lib/gen_eq.cpp
  backends/p4tools/common/lib/table_utils.cpp
  backends/p4tools/common/lib/taint.cpp
  backends/p4tools/common/lib/util.cpp
  backends/p4tools/modules/testgen/core/program_info.cpp
  backends/p4tools/modules/testgen/core/small_step/abstract_stepper.cpp
  backends/p4tools/modules/testgen/core/small_step/cmd_stepper.cpp
  backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
  backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
  backends/p4tools/modules/testgen/core/small_step/small_step.cpp
  backends/p4tools/modules/testgen/core/small_step/table_stepper.cpp
  backends/p4tools/modules/testgen/core/small_step/table_stepper.h
  backends/p4tools/modules/testgen/lib/execution_state.cpp
  backends/p4tools/modules/testgen/targets/bmv2/cmd_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/concolic.cpp
  backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/p4_asserts_parser.cpp
  backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
  backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/small-step/p4_asserts_parser_test.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/test_backend/ptf.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/test_backend/stf.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test_backend/stf.cpp
  backends/p4tools/modules/testgen/targets/ebpf/backend/stf/stf.cpp
  backends/p4tools/modules/testgen/targets/ebpf/cmd_stepper.cpp
  backends/p4tools/modules/testgen/targets/ebpf/expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/ebpf/program_info.cpp
  backends/p4tools/modules/testgen/targets/ebpf/test_backend.cpp
  backends/p4tools/modules/testgen/targets/pna/dpdk/cmd_stepper.cpp
  backends/p4tools/modules/testgen/targets/pna/dpdk/program_info.cpp
  backends/p4tools/modules/testgen/targets/pna/shared_expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/pna/shared_table_stepper.cpp
  backends/p4tools/modules/testgen/targets/pna/test_backend.cpp
  backends/p4tools/modules/testgen/test/lib/format_int.cpp
  backends/p4tools/modules/testgen/test/lib/taint.cpp
  backends/p4tools/modules/testgen/test/z3-solver/constraints.cpp
  ir/expression.cpp
  ir/expression.def
  ir/irutils.cpp
  ir/irutils.h
  lib/hash.h
  midend/booleanKeys.cpp
  midend/saturationElim.cpp
  test/gtest/transforms.cpp
Labels: testgen, core

#4653 Improve error message when shifting int by non-const
  frontends/p4/typeChecking/typeChecker.cpp
  testdata/p4_16_errors/shift-int-non-const.p4
  testdata/p4_16_errors_outputs/issue2206.p4-stderr
  testdata/p4_16_errors_outputs/shift-int-non-const.p4
  testdata/p4_16_errors_outputs/shift-int-non-const.p4-stderr
  testdata/p4_16_samples/shift-int-const.p4
  testdata/p4_16_samples_outputs/shift-int-const-first.p4
  testdata/p4_16_samples_outputs/shift-int-const-frontend.p4
  testdata/p4_16_samples_outputs/shift-int-const-midend.p4
  testdata/p4_16_samples_outputs/shift-int-const.p4
  testdata/p4_16_samples_outputs/shift-int-const.p4-stderr
Labels: enhancement, core

#4644 Fix missing declaration of custom externs in the generated eBPF/uBPF header file.
  backends/ebpf/CMakeLists.txt
  backends/ebpf/ebpfProgram.cpp
  backends/ebpf/ebpfProgram.h
  backends/ebpf/ebpfType.cpp
  backends/ebpf/ebpfType.h
  backends/ebpf/runtime/runtime.mk
  backends/ubpf/ubpfProgram.cpp
  backends/ubpf/ubpfProgram.h
  backends/ubpf/ubpfType.cpp
  backends/ubpf/ubpfType.h
Labels: ebpf, run-ubuntu18

#4637 P4Tc - Change parameter for kfunc 'bpf_p4tc_entry_create_on_miss'
  backends/tc/ebpfCodeGen.cpp
  testdata/p4tc_samples_outputs/add_entry_1_example_control_blocks.c
  testdata/p4tc_samples_outputs/add_entry_3_example_control_blocks.c
  testdata/p4tc_samples_outputs/add_entry_example_control_blocks.c
Labels: run-sanitizer

#4655 Fixes to lib/hash and lib/big_int_util.
  BUILD.bazel
  backends/p4tools/common/lib/symbolic_env.cpp
  ir/expression.cpp
  lib/alloc_trace.h
  lib/big_int.h
  lib/big_int_util.h
  lib/hash.h
Labels: core, run-ubuntu18, run-sanitizer, run-static

#4254 Add support for a clang-tidy linter to CMake. Add a files utility function to P4CUtils.cmake.
  .clang-tidy
  CMakeLists.txt
  cmake/Linters.cmake
  cmake/P4CUtils.cmake
Labels: test-infrastructure

#4650 Merge TestgenCompilerTarget into TestgenTarget.
  backends/p4tools/common/CMakeLists.txt
  backends/p4tools/common/compiler/compiler_result.cpp
  backends/p4tools/common/compiler/compiler_result.h
  backends/p4tools/common/compiler/compiler_target.cpp
  backends/p4tools/common/compiler/compiler_target.h
  backends/p4tools/common/core/target.cpp
  backends/p4tools/common/core/target.h
  backends/p4tools/common/options.cpp
  backends/p4tools/common/options.h
  backends/p4tools/common/p4ctool.h
  backends/p4tools/modules/testgen/CMakeLists.txt
  backends/p4tools/modules/testgen/core/compiler_result.cpp
  backends/p4tools/modules/testgen/core/compiler_result.h
  backends/p4tools/modules/testgen/core/compiler_target.cpp
  backends/p4tools/modules/testgen/core/program_info.cpp
  backends/p4tools/modules/testgen/core/program_info.h
  backends/p4tools/modules/testgen/core/target.cpp
  backends/p4tools/modules/testgen/core/target.h
  backends/p4tools/modules/testgen/main.cpp
  backends/p4tools/modules/testgen/options.cpp
  backends/p4tools/modules/testgen/register.h.in
  backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
  backends/p4tools/modules/testgen/targets/bmv2/bmv2.cpp
  backends/p4tools/modules/testgen/targets/bmv2/compiler_result.cpp
  backends/p4tools/modules/testgen/targets/bmv2/compiler_result.h
  backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
  backends/p4tools/modules/testgen/targets/bmv2/program_info.h
  backends/p4tools/modules/testgen/targets/bmv2/register.h
  backends/p4tools/modules/testgen/targets/bmv2/target.cpp
  backends/p4tools/modules/testgen/targets/bmv2/target.h
  backends/p4tools/modules/testgen/targets/ebpf/CMakeLists.txt
  backends/p4tools/modules/testgen/targets/ebpf/ebpf.cpp
  backends/p4tools/modules/testgen/targets/ebpf/ebpf.h
  backends/p4tools/modules/testgen/targets/ebpf/program_info.cpp
  backends/p4tools/modules/testgen/targets/ebpf/register.h
  backends/p4tools/modules/testgen/targets/ebpf/target.cpp
  backends/p4tools/modules/testgen/targets/ebpf/target.h
  backends/p4tools/modules/testgen/targets/pna/CMakeLists.txt
  backends/p4tools/modules/testgen/targets/pna/dpdk/program_info.cpp
  backends/p4tools/modules/testgen/targets/pna/pna.cpp
  backends/p4tools/modules/testgen/targets/pna/pna.h
  backends/p4tools/modules/testgen/targets/pna/register.h
  backends/p4tools/modules/testgen/targets/pna/target.cpp
  backends/p4tools/modules/testgen/targets/pna/target.h
  backends/p4tools/modules/testgen/test/gtest_utils.cpp
  backends/p4tools/modules/testgen/testgen.cpp
  backends/p4tools/modules/testgen/toolname.h
Labels: testgen

#3930 Link against the Boehm-Demers-Weiser Garbage Collector using FetchContent.
  CMakeLists.txt
  backends/p4tools/cmake/common.cmake
  backends/p4tools/common/control_plane/CMakeLists.txt
  cmake/BDWGC.cmake
  cmake/bdwgc.patch
  frontends/CMakeLists.txt
  ir/CMakeLists.txt
  ir/visitor.cpp
  lib/CMakeLists.txt
  lib/bitvec.h
  lib/gc.cpp
  lib/indent.cpp
  lib/log.cpp
  tools/ci-build.sh
  tools/install_fedora_deps.sh
  tools/install_mac_deps.sh
Labels: core, run-ubuntu18, run-sanitizer

#4657 [#4656] Explicitly delay constant folding of only action enum `IR::SwitchCase` `label` expressions, instead of delaying constant folding of all `IR::Mux` expressions
  frontends/common/constantFolding.cpp
  frontends/common/constantFolding.h
  frontends/p4/frontend.cpp
  testdata/p4_16_errors_outputs/issue3699.p4-stderr
  testdata/p4_16_samples/issue3699.p4
  testdata/p4_16_samples/issue4656_const_fold_generic_switch_label_expr.p4
  testdata/p4_16_samples/issue4656_fold_bit_width_const_mux_expr.p4
  testdata/p4_16_samples_outputs/issue3699-first.p4
  testdata/p4_16_samples_outputs/issue3699-frontend.p4
  testdata/p4_16_samples_outputs/issue3699.p4
  testdata/p4_16_samples_outputs/issue3699.p4-stderr
  testdata/p4_16_samples_outputs/issue4656_const_fold_generic_switch_label_expr-first.p4
  testdata/p4_16_samples_outputs/issue4656_const_fold_generic_switch_label_expr-frontend.p4
  testdata/p4_16_samples_outputs/issue4656_const_fold_generic_switch_label_expr-midend.p4
  testdata/p4_16_samples_outputs/issue4656_const_fold_generic_switch_label_expr.p4
  testdata/p4_16_samples_outputs/issue4656_const_fold_generic_switch_label_expr.p4-stderr
  testdata/p4_16_samples_outputs/issue4656_fold_bit_width_const_mux_expr-first.p4
  testdata/p4_16_samples_outputs/issue4656_fold_bit_width_const_mux_expr-frontend.p4
  testdata/p4_16_samples_outputs/issue4656_fold_bit_width_const_mux_expr-midend.p4
  testdata/p4_16_samples_outputs/issue4656_fold_bit_width_const_mux_expr.p4
  testdata/p4_16_samples_outputs/issue4656_fold_bit_width_const_mux_expr.p4-stderr
Labels: core, p4-spec

#4664 Explicitly include hash.hpp for Ubuntu 18.04.
  lib/big_int_util.h
Labels: core, run-ubuntu18

#4669 Replace IR::getBitType with IR::Type_Bits::get.
  backends/p4tools/common/compiler/convert_hs_index.cpp
  backends/p4tools/common/lib/taint.cpp
  backends/p4tools/common/lib/util.cpp
  backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
  backends/p4tools/modules/testgen/core/small_step/table_stepper.cpp
  backends/p4tools/modules/testgen/lib/execution_state.cpp
  backends/p4tools/modules/testgen/lib/final_state.cpp
  backends/p4tools/modules/testgen/lib/test_backend.cpp
  backends/p4tools/modules/testgen/targets/bmv2/cmd_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/concolic.cpp
  backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/p4_refers_to_parser.cpp
  backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/test_backend/ptf.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/test_backend/stf.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
  backends/p4tools/modules/testgen/targets/ebpf/cmd_stepper.cpp
  backends/p4tools/modules/testgen/targets/ebpf/expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/ebpf/program_info.cpp
  backends/p4tools/modules/testgen/targets/ebpf/test_backend.cpp
  backends/p4tools/modules/testgen/targets/pna/dpdk/cmd_stepper.cpp
  backends/p4tools/modules/testgen/targets/pna/shared_program_info.cpp
  backends/p4tools/modules/testgen/targets/pna/test_backend.cpp
  backends/p4tools/modules/testgen/test/lib/format_int.cpp
  backends/p4tools/modules/testgen/test/lib/taint.cpp
  backends/p4tools/modules/testgen/test/z3-solver/constraints.cpp
  ir/irutils.cpp
  ir/irutils.h
  midend/booleanKeys.cpp
  midend/parserUnroll.cpp
  midend/parserUnroll.h
Labels: core

#4668 RemoveUnusedDeclarations - make helpers protected
  frontends/p4/unusedDeclarations.h
Labels: core

#4543 Aggressively clean up the Protobuf CMake dependency.
  CMakeLists.txt
  README.md
  backends/dpdk/CMakeLists.txt
  backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
  cmake/Abseil.cmake
  cmake/Protobuf.cmake
  control-plane/CMakeLists.txt
Labels: dependencies, run-ubuntu18, run-sanitizer

#4677 Generalization & minor refactoring in RenameMap
  frontends/p4/uniqueNames.cpp
  frontends/p4/uniqueNames.h
Labels: core

#4676 Add string_view and string conversion operators and functions to cstring
  lib/cstring.cpp
  lib/cstring.h
Labels: core

#4682 Facilitate inheritance from RenameSymbols pass, deduplicate code
  frontends/p4/uniqueNames.cpp
  frontends/p4/uniqueNames.h
Labels: core

#4612 Set type for LAnd, LOr, LNot to be Type_Boolean if unknown.
  ir/expression.def
Labels: core

#4678 Improve `BUG_CHECK` internals
  BUILD.bazel
  lib/CMakeLists.txt
  lib/bug_helper.h
  lib/error_helper.h
  lib/error_reporter.h
  lib/exceptions.h
  lib/source_file.cpp
Labels: core, run-ubuntu18, run-sanitizer, run-static

#4687 Remove no-longer-used *.p4info.txt files
  testdata/p4_16_errors_outputs/issue-2123_e.p4.p4info.txt
  testdata/p4_16_errors_outputs/issue1777-bmv2.p4.p4info.txt
  testdata/p4_16_errors_outputs/issue1803_same_table_name.p4.p4info.txt
  testdata/p4_16_errors_outputs/issue2283_2-bmv2.p4.p4info.txt
  testdata/p4_16_errors_outputs/issue3299.p4.p4info.txt
  testdata/p4_16_errors_outputs/issue532.p4.p4info.txt
  testdata/p4_16_errors_outputs/table-entries-lpm-2.p4.p4info.txt
  testdata/p4_16_errors_outputs/table-entries-optional-2-bmv2.p4.p4info.txt
  testdata/p4_16_samples_outputs/fabric_20190420/fabric.p4.p4info.txt
  testdata/p4_16_samples_outputs/omec/up4.p4.p4info.txt
  testdata/p4_16_samples_outputs/pins/pins_fabric.p4.p4info.txt
  testdata/p4_16_samples_outputs/pins/pins_middleblock.p4.p4info.txt
  testdata/p4_16_samples_outputs/pins/pins_wbb.p4.p4info.txt
Labels: test-infrastructure

#4679 Workaround for gcc-11.4/draft 2x spec flaw
  ir/id.h
  ir/namemap.h
  lib/cstring.h
Labels: core

#4681 irgen: Generate explicit instantiations
  tools/ir-generator/irclass.cpp
  tools/ir-generator/irclass.h
Labels: core

#4692 Add a release template to the compiler.
  .github/release.yml
  .github/workflows/ci-auto-release.yml
  .github/workflows/ci-release.yml
Labels: test-infrastructure

#4675 Fix extern pipeline name in template file
  backends/tc/ebpfCodeGen.cpp
  backends/tc/tc.def
  testdata/p4tc_samples_outputs/add_entry_1_example_parser.h
  testdata/p4tc_samples_outputs/add_entry_3_example_parser.h
  testdata/p4tc_samples_outputs/add_entry_example_parser.h
  testdata/p4tc_samples_outputs/calculator_parser.h
  testdata/p4tc_samples_outputs/checksum_parser.h
  testdata/p4tc_samples_outputs/const_entries_range_mask_parser.h
  testdata/p4tc_samples_outputs/default_action_example_01_parser.h
  testdata/p4tc_samples_outputs/default_action_example_parser.h
  testdata/p4tc_samples_outputs/default_action_with_param_01_parser.h
  testdata/p4tc_samples_outputs/default_action_with_param_parser.h
  testdata/p4tc_samples_outputs/default_hit_const_example_parser.h
  testdata/p4tc_samples_outputs/drop_packet_example_parser.h
  testdata/p4tc_samples_outputs/global_action_example_01_parser.h
  testdata/p4tc_samples_outputs/global_action_example_02_parser.h
  testdata/p4tc_samples_outputs/hash1_parser.h
  testdata/p4tc_samples_outputs/ipip_parser.h
  testdata/p4tc_samples_outputs/matchtype_parser.h
  testdata/p4tc_samples_outputs/mix_matchtype_example_parser.h
  testdata/p4tc_samples_outputs/multiple_tables_example_01_parser.h
  testdata/p4tc_samples_outputs/multiple_tables_example_02_parser.h
  testdata/p4tc_samples_outputs/name_annotation_example_parser.h
  testdata/p4tc_samples_outputs/no_table_example_parser.h
  testdata/p4tc_samples_outputs/noaction_example_01_parser.h
  testdata/p4tc_samples_outputs/noaction_example_02_parser.h
  testdata/p4tc_samples_outputs/nummask_annotation_example_parser.h
  testdata/p4tc_samples_outputs/send_to_port_example.template
  testdata/p4tc_samples_outputs/send_to_port_example_parser.h
  testdata/p4tc_samples_outputs/set_entry_timer_example_parser.h
  testdata/p4tc_samples_outputs/simple_exact_example_parser.h
  testdata/p4tc_samples_outputs/simple_extern_example.template
  testdata/p4tc_samples_outputs/simple_extern_example_parser.h
  testdata/p4tc_samples_outputs/simple_lpm_example_parser.h
  testdata/p4tc_samples_outputs/simple_ternary_example_parser.h
  testdata/p4tc_samples_outputs/size_param_example_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_01_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_02_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_03_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_04_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_05_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_06_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_07_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_08_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_09_parser.h
  testdata/p4tc_samples_outputs/tc_type_annotation_example_parser.h
  testdata/p4tc_samples_outputs/test_ipv6_example_parser.h
Labels: p4tc

#4611 Add support for new platform property annotations for P4Runtime.
  CMakeLists.txt
  bazel/p4c_deps.bzl
  control-plane/p4RuntimeAnnotations.h
  control-plane/p4RuntimeSerializer.cpp
  testdata/p4_16_samples/pkginfo_annotation.p4
  testdata/p4_16_samples_outputs/pkginfo_annotation-first.p4
  testdata/p4_16_samples_outputs/pkginfo_annotation-frontend.p4
  testdata/p4_16_samples_outputs/pkginfo_annotation-midend.p4
  testdata/p4_16_samples_outputs/pkginfo_annotation.p4
  testdata/p4_16_samples_outputs/pkginfo_annotation.p4-stderr
  testdata/p4_16_samples_outputs/pkginfo_annotation.p4.entries.txtpb
  testdata/p4_16_samples_outputs/pkginfo_annotation.p4.p4info.txtpb
Labels: control-plane
