Repository p4lang/p4c, pull requests merged in 2024-08, with the labels that each got.

#4840 Make SymbolicVariable part of the core IR.
  backends/p4tools/p4tools.def
  ir/expression.def
Labels: core

#4847 Minor fix : Heading of portable_common
  backends/bmv2/portable_common/README.md
Labels: documentation

#4843 Fix incorrect BMv2 include.
  backends/common/portableProgramStructure.cpp
  backends/common/portableProgramStructure.h
Labels: bmv2

#4849 Docs : Changelogs release update for v1.2.4.14
  CHANGELOG.md
Labels: documentation

#4848 Feat: PR Preview Workflow via GitHub Pages
  .github/workflows/deploy-docs.yml
Labels: infrastructure, documentation

#4830 Ensure correct overload for diagnose() is called even in Transform context
  lib/error_reporter.h
  lib/source_file.h
  testdata/p4_16_errors_outputs/issue3727.p4-stderr
  testdata/p4_16_errors_outputs/minWidth.p4-stderr
  testdata/p4_16_errors_outputs/stack_e.p4-stderr
  testdata/p4_16_errors_outputs/type-in-expr.p4-stderr
  testdata/p4_16_samples_outputs/psa-dpdk-lpm-match-err5.p4-error
  testdata/p4_16_samples_outputs/psa-dpdk-lpm-match-err5.p4-stderr
Labels: core

#4842 Support of Digest extern in P4TC
  backends/ebpf/psa/externs/ebpfPsaDigest.h
  backends/tc/backend.cpp
  backends/tc/ebpfCodeGen.cpp
  backends/tc/ebpfCodeGen.h
  backends/tc/introspection.cpp
  backends/tc/runtime/pna.h
  backends/tc/tc.def
  backends/tc/tcExterns.cpp
  backends/tc/tcExterns.h
  p4include/tc/pna.p4
  testdata/p4tc_samples/digest.p4
  testdata/p4tc_samples/digest_01.p4
  testdata/p4tc_samples_outputs/digest.json
  testdata/p4tc_samples_outputs/digest.p4-stderr
  testdata/p4tc_samples_outputs/digest.template
  testdata/p4tc_samples_outputs/digest_01.json
  testdata/p4tc_samples_outputs/digest_01.p4-stderr
  testdata/p4tc_samples_outputs/digest_01.template
  testdata/p4tc_samples_outputs/digest_01_control_blocks.c
  testdata/p4tc_samples_outputs/digest_01_parser.c
  testdata/p4tc_samples_outputs/digest_01_parser.h
  testdata/p4tc_samples_outputs/digest_control_blocks.c
  testdata/p4tc_samples_outputs/digest_parser.c
  testdata/p4tc_samples_outputs/digest_parser.h
Labels: p4tc, run-sanitizer

#4855 Fix: PR Preview URL to Use Base Repository
  .github/workflows/deploy-docs.yml
Labels: documentation

#4861 Bump Documentation build workflow action from Doxygen `v1.11.0` to `v1.12.0`
  .github/workflows/deploy-docs.yml
  README.md
  docs/doxygen/doxygen.cfg
  docs/doxygen/p4c_footer.html
  docs/doxygen/p4c_header.html
  docs/doxygen/p4c_layout.xml
Labels: documentation

#4858 Fixup/cleanup IR::Type::width_bits()
  backends/bmv2/common/control.h
  backends/bmv2/psa_switch/psaSwitch.h
  backends/p4tools/common/lib/variables.cpp
  backends/p4tools/modules/testgen/test/lib/taint.cpp
  ir/base.def
  ir/expression.def
  ir/type.def
Labels: core, breaking-change

#4852 [P4Testgen] Represent bits of width zero as an empty string.
  backends/p4tools/common/lib/format_int.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test_backend/ptf.cpp
  backends/p4tools/modules/testgen/test/lib/format_int.cpp
Labels: p4tools

#4865 Fix ASAN issue in lib/cstring.
  lib/cstring.cpp
  lib/cstring.h
Labels: core

#4850 Docs : Content Organization and Documentation Updates
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  backends/bmv2/README.md
  backends/bmv2/pna_nic/README.md
  backends/bmv2/portable_common/README.md
  backends/dpdk/README.md
  backends/ebpf/README.md
  backends/ebpf/psa/README.md
  backends/graphs/README.md
  backends/p4fmt/README.md
  backends/p4test/README.md
  backends/p4tools/CONTRIBUTORS.md
  backends/p4tools/README.md
  backends/p4tools/modules/smith/README.md
  backends/p4tools/modules/testgen/README.md
  backends/p4tools/modules/testgen/benchmarks/README.md
  backends/p4tools/modules/testgen/targets/bmv2/test/README.md
  backends/tc/README.md
  backends/ubpf/README.md
  backends/ubpf/docs/EXAMPLES.md
  backends/ubpf/tests/README.md
  docs/CodingStandardPhilosophy.md
  docs/IR.md
  docs/README.md
  docs/doxygen/01_overview.md
  docs/doxygen/Doxymain.md
  docs/doxygen/doxygen.cfg
  docs/doxygen/p4c_header.html
  docs/doxygen/p4c_layout.xml
  frontends/README.md
  ir/README.md
  lib/README.md
  midend/README.md
Labels: documentation

#4856 Allow concatenation of string literals at compile time
  frontends/common/constantFolding.cpp
  frontends/p4/frontend.cpp
  frontends/p4/parseAnnotations.cpp
  frontends/p4/typeChecking/bindVariables.cpp
  frontends/p4/typeChecking/bindVariables.h
  frontends/p4/typeChecking/typeCheckExpr.cpp
  frontends/p4/validateStringAnnotations.h
  testdata/p4_16_errors/spec-issue1297-string-cat-err-0.p4
  testdata/p4_16_errors/spec-issue1297-string-cat-err-1.p4
  testdata/p4_16_errors/spec-issue1297-string-cat-err-2-anno.p4
  testdata/p4_16_errors/spec-issue1297-string-cat-err-3-anno.p4
  testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-0.p4
  testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-0.p4-stderr
  testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-1.p4
  testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-1.p4-stderr
  testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-2-anno.p4
  testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-2-anno.p4-stderr
  testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-3-anno.p4
  testdata/p4_16_errors_outputs/spec-issue1297-string-cat-err-3-anno.p4-stderr
  testdata/p4_16_samples/spec-issue1297-string-cat.p4
  testdata/p4_16_samples_outputs/spec-issue1297-string-cat-first.p4
  testdata/p4_16_samples_outputs/spec-issue1297-string-cat-frontend.p4
  testdata/p4_16_samples_outputs/spec-issue1297-string-cat-midend.p4
  testdata/p4_16_samples_outputs/spec-issue1297-string-cat.p4
  testdata/p4_16_samples_outputs/spec-issue1297-string-cat.p4-stderr
Labels: p4-spec

#4876 Docs:Content Organization & Add 'Frontend' and 'Midend' Sections
  backends/bmv2/pna_nic/README.md
  backends/bmv2/portable_common/README.md
  backends/p4test/README.md
  backends/p4tools/CONTRIBUTORS.md
  docs/IR.md
  docs/doxygen/doxygen.cfg
  frontends/README.md
  ir/README.md
  lib/README.md
  midend/README.md
Labels: documentation

#4881 Fix linter complaints in the validateStringAnnotations pass and enable -werror for MacOS.
  .github/workflows/ci-test-mac.yml
  frontends/p4/validateStringAnnotations.h
Labels: core, run-sanitizer

#4791 Reenable compilation tests for P4Smith.
  .github/workflows/ci-p4tools.yml
  .github/workflows/ci-test-mac.yml
  backends/p4tools/modules/smith/CMakeLists.txt
  backends/p4tools/modules/smith/common/declarations.cpp
  backends/p4tools/modules/smith/common/expressions.cpp
  backends/p4tools/modules/smith/common/expressions.h
  backends/p4tools/modules/smith/common/parser.cpp
  backends/p4tools/modules/smith/common/probabilities.cpp
  backends/p4tools/modules/smith/common/probabilities.h
  backends/p4tools/modules/smith/common/scope.cpp
  backends/p4tools/modules/smith/common/scope.h
  backends/p4tools/modules/smith/common/statements.cpp
  backends/p4tools/modules/smith/scripts/compilation-test.sh
  backends/p4tools/modules/smith/smith.cpp
  backends/p4tools/modules/smith/targets/bmv2/CMakeLists.txt
  backends/p4tools/modules/smith/targets/bmv2/psa.cpp
  backends/p4tools/modules/smith/targets/bmv2/test/P4Tests.cmake
  backends/p4tools/modules/smith/targets/bmv2/v1model.cpp
  backends/p4tools/modules/smith/targets/generic/target.cpp
  backends/p4tools/modules/smith/targets/generic/test/P4Tests.cmake
  backends/p4tools/modules/smith/targets/nic/CMakeLists.txt
  backends/p4tools/modules/smith/targets/nic/expressions.cpp
  backends/p4tools/modules/smith/targets/nic/expressions.h
  backends/p4tools/modules/smith/targets/nic/target.cpp
  backends/p4tools/modules/smith/targets/nic/target.h
  backends/p4tools/modules/smith/targets/nic/test/P4Tests.cmake
  backends/p4tools/modules/smith/targets/tofino/target.cpp
Labels: p4tools

#4880 Reduce extern parameters size to 64 bytes
  backends/tc/runtime/pna.h
Labels: p4tc

#4879 Remove priority field from ternary table's action
  backends/tc/ebpfCodeGen.cpp
  testdata/p4tc_samples_outputs/default_hit_const_example_control_blocks.c
  testdata/p4tc_samples_outputs/matchtype_control_blocks.c
  testdata/p4tc_samples_outputs/mix_matchtype_example_control_blocks.c
  testdata/p4tc_samples_outputs/multiple_tables_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/multiple_tables_example_02_control_blocks.c
  testdata/p4tc_samples_outputs/simple_ternary_example_control_blocks.c
Labels: p4tc

#4841 [P4Tools] Clean up the P4Tools GTest infrastructure.
  backends/p4tools/BUILD.bazel
  backends/p4tools/modules/smith/targets/generic/test/smith_for_in_loop_test.cpp
  backends/p4tools/modules/smith/targets/generic/test/smith_for_loop_test.cpp
  backends/p4tools/modules/testgen/lib/continuation.h
  backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
  backends/p4tools/modules/testgen/targets/bmv2/test/gtest_utils.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/gtest_utils.h
  backends/p4tools/modules/testgen/targets/bmv2/test/small-step/binary.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/small-step/p4_asserts_parser_test.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/small-step/reachability.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/small-step/unary.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/small-step/value.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/test_backend/ptf.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/test_backend/ptf.h
  backends/p4tools/modules/testgen/targets/bmv2/test/test_backend/stf.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/test_backend/stf.h
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/api_test.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/benchmark.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/control_plane_filter_test.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/output_option_test.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/z3-solver/asrt_model.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/z3-solver/expressions.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/z3-solver/saturation_arithm.cpp
  backends/p4tools/modules/testgen/test/gtest_utils.cpp
  backends/p4tools/modules/testgen/test/gtest_utils.h
  backends/p4tools/modules/testgen/test/lib/format_int.cpp
  backends/p4tools/modules/testgen/test/lib/format_int.h
  backends/p4tools/modules/testgen/test/lib/p4info_api.cpp
  backends/p4tools/modules/testgen/test/lib/p4info_api.h
  backends/p4tools/modules/testgen/test/lib/taint.cpp
  backends/p4tools/modules/testgen/test/lib/taint.h
  backends/p4tools/modules/testgen/test/small-step/util.cpp
  backends/p4tools/modules/testgen/test/small-step/util.h
  backends/p4tools/modules/testgen/test/z3-solver/constraints.cpp
Labels: p4tools

#4885 Trim overlong source fragments in error messages
  lib/source_file.cpp
  lib/source_file.h
  testdata/p4_14_samples_outputs/sai_p4.p4-stderr
  testdata/p4_16_errors_outputs/issue2835-bmv2.p4-stderr
  testdata/p4_16_pna_errors_outputs/pna-add-on-miss-err.p4-error
  testdata/p4_16_pna_errors_outputs/pna-example-addhit.p4-error
  testdata/p4_16_pna_errors_outputs/pna-example-miss.p4-error
  testdata/p4_16_samples_outputs/dash/dash-pipeline-pna-dpdk.p4-stderr
  testdata/p4_16_samples_outputs/dash/dash-pipeline-v1model-bmv2.p4-stderr
  testdata/p4_16_samples_outputs/invalid-hdr-warnings1.p4-stderr
  testdata/p4_16_samples_outputs/invalid-hdr-warnings6.p4-stderr
  testdata/p4_16_samples_outputs/issue4796.p4-stderr
  testdata/p4_16_samples_outputs/issue982.p4-stderr
  testdata/p4_16_samples_outputs/pins/pins_fabric.p4-stderr
  testdata/p4_16_samples_outputs/pins/pins_middleblock.p4-stderr
  testdata/p4_16_samples_outputs/pna-dpdk-invalid-hdr-warnings6.p4-stderr
  testdata/p4tc_samples_outputs/global_action_example_01.p4-stderr
Labels: core

#4868 Update BDWGC.
  cmake/BDWGC.cmake
  cmake/bdwgc.patch
  ir/visitor.cpp
  lib/bitvec.h
  lib/cstring.cpp
  lib/gc.cpp
  lib/indent.cpp
  lib/log.cpp
Labels: infrastructure

#4851 Add operator< to some compiler classes
  frontends/common/constantParsing.cpp
  frontends/common/constantParsing.h
  ir/id.h
  lib/ordered_map.h
  lib/ordered_set.h
  tools/ir-generator/irclass.cpp
  tools/ir-generator/irclass.h
  tools/ir-generator/methods.cpp
Labels: core

#4890 Remove 4 tests that are completely identical to other tests that remain
  testdata/p4_16_samples/inline1-bmv2.p4
  testdata/p4_16_samples/issue1566.p4
  testdata/p4_16_samples/issue1914-2.p4
  testdata/p4_16_samples/issue655.p4
  testdata/p4_16_samples_outputs/inline1-bmv2-first.p4
  testdata/p4_16_samples_outputs/inline1-bmv2-frontend.p4
  testdata/p4_16_samples_outputs/inline1-bmv2-midend.p4
  testdata/p4_16_samples_outputs/inline1-bmv2.p4
  testdata/p4_16_samples_outputs/inline1-bmv2.p4-stderr
  testdata/p4_16_samples_outputs/inline1-bmv2.p4.entries.txtpb
  testdata/p4_16_samples_outputs/inline1-bmv2.p4.p4info.txtpb
  testdata/p4_16_samples_outputs/issue1566-first.p4
  testdata/p4_16_samples_outputs/issue1566-frontend.p4
  testdata/p4_16_samples_outputs/issue1566-midend.p4
  testdata/p4_16_samples_outputs/issue1566.p4
  testdata/p4_16_samples_outputs/issue1566.p4-stderr
  testdata/p4_16_samples_outputs/issue1566.p4.entries.txtpb
  testdata/p4_16_samples_outputs/issue1566.p4.p4info.txtpb
  testdata/p4_16_samples_outputs/issue1914-2-first.p4
  testdata/p4_16_samples_outputs/issue1914-2-frontend.p4
  testdata/p4_16_samples_outputs/issue1914-2-midend.p4
  testdata/p4_16_samples_outputs/issue1914-2.p4
  testdata/p4_16_samples_outputs/issue1914-2.p4-stderr
  testdata/p4_16_samples_outputs/issue655-first.p4
  testdata/p4_16_samples_outputs/issue655-frontend.p4
  testdata/p4_16_samples_outputs/issue655-midend.p4
  testdata/p4_16_samples_outputs/issue655.p4
  testdata/p4_16_samples_outputs/issue655.p4-stderr
  testdata/p4_16_samples_outputs/issue655.p4.entries.txtpb
  testdata/p4_16_samples_outputs/issue655.p4.p4info.txtpb
Labels: infrastructure
