Repository p4lang/p4c, pull requests merged in 2024-11, with the labels that each got.

#4993 Fix case of default CMake build mode.
  CMakeLists.txt
Labels: infrastructure

#4997 Remove CMAKE_BUILD_TYPE values that do not work when building Z3
  README.md
  bootstrap.sh
  tools/ci-build.sh
  tools/debian-build/packaging.conf
Labels: infrastructure, documentation

#4996 Miscellaneous small Tofino fixes for compilation.
  backends/tofino/bf-p4c/CMakeLists.txt
  backends/tofino/bf-p4c/arch/arch.cpp
  backends/tofino/bf-p4c/arch/fromv1.0/programStructure.cpp
  backends/tofino/bf-p4c/arch/fromv1.0/v1_converters.cpp
  backends/tofino/bf-p4c/control-plane/bfruntime_arch_handler.h
  backends/tofino/bf-p4c/ir/mau.cpp
  backends/tofino/bf-p4c/mau/add_always_run.cpp
  backends/tofino/bf-p4c/mau/instruction_selection.cpp
  backends/tofino/bf-p4c/mau/mau_power.cpp
  backends/tofino/bf-p4c/mau/simple_power_graph.cpp
  backends/tofino/bf-p4c/phv/phv_fields.cpp
Labels: tofino

#4995 Try to fix clang compilation failures with the `-fsized-deallocation` option.
  CMakeLists.txt
  backends/p4tools/common/control_plane/CMakeLists.txt
  backends/p4tools/p4tools.def
  backends/tofino/bf-p4c/CMakeLists.txt
  frontends/CMakeLists.txt
  ir/CMakeLists.txt
  ir/type.def
Labels: run-ubuntu18, run-validation, run-sanitizer, infrastructure, run-static

#5003 Docs : Changelogs release update for `v1.2.4.16` & `v1.2.4.17`
  CHANGELOG.md
Labels: documentation

#4999 Enable handling of arbitrary if statements within actions for BMv2 back end
  backends/bmv2/common/action.cpp
  backends/bmv2/common/action.h
  backends/bmv2/simple_switch/midend.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2STFXfail.cmake
  testdata/p4_16_samples/nested-actions-with-return-exit1.p4
  testdata/p4_16_samples_outputs/nested-actions-with-return-exit1-first.p4
  testdata/p4_16_samples_outputs/nested-actions-with-return-exit1-frontend.p4
  testdata/p4_16_samples_outputs/nested-actions-with-return-exit1-midend.p4
  testdata/p4_16_samples_outputs/nested-actions-with-return-exit1.p4
  testdata/p4_16_samples_outputs/nested-actions-with-return-exit1.p4-stderr
  testdata/p4_16_samples_outputs/nested-actions-with-return-exit1.p4.entries.txtpb
  testdata/p4_16_samples_outputs/nested-actions-with-return-exit1.p4.p4info.txtpb
Labels: bmv2

#5004 Fix broken Tofino build.
  backends/p4tools/common/core/z3_solver.cpp
  backends/tofino/bf-p4c/arch/fromv1.0/checksum.cpp
  backends/tofino/bf-p4c/arch/fromv1.0/meter.cpp
  backends/tofino/bf-p4c/arch/fromv1.0/programStructure.cpp
  backends/tofino/bf-p4c/arch/fromv1.0/stateful_alu.cpp
  backends/tofino/bf-p4c/arch/v1model.cpp
  backends/tofino/bf-p4c/asm.cpp
  backends/tofino/bf-p4c/backend.cpp
  backends/tofino/bf-p4c/bf-p4c-options.h
  backends/tofino/bf-p4c/common/bridged_packing.cpp
  backends/tofino/bf-p4c/common/extract_maupipe.cpp
  backends/tofino/bf-p4c/common/parse_annotations.h
  backends/tofino/bf-p4c/control-plane/bfruntime_arch_handler.h
  backends/tofino/bf-p4c/ir/dbprint-tofino.cpp
  backends/tofino/bf-p4c/ir/mau.cpp
  backends/tofino/bf-p4c/ir/parde.def
  backends/tofino/bf-p4c/lib/cmp.h
  backends/tofino/bf-p4c/logging/manifest.cpp
  backends/tofino/bf-p4c/logging/phv_logging.cpp
  backends/tofino/bf-p4c/logging/resources_parser.cpp
  backends/tofino/bf-p4c/mau/asm_output.cpp
  backends/tofino/bf-p4c/mau/gen_prim_json.cpp
  backends/tofino/bf-p4c/mau/instruction_selection.cpp
  backends/tofino/bf-p4c/mau/mau_alloc.cpp
  backends/tofino/bf-p4c/mau/simple_power_graph.cpp
  backends/tofino/bf-p4c/mau/simple_power_graph.h
  backends/tofino/bf-p4c/mau/split_gateways.cpp
  backends/tofino/bf-p4c/mau/stateful_alu.cpp
  backends/tofino/bf-p4c/mau/table_dependency_graph.cpp
  backends/tofino/bf-p4c/mau/table_flow_graph.cpp
  backends/tofino/bf-p4c/mau/table_mutex.cpp
  backends/tofino/bf-p4c/mau/table_summary.cpp
  backends/tofino/bf-p4c/mau/tofino/memories.cpp
  backends/tofino/bf-p4c/mau/validate_actions.cpp
  backends/tofino/bf-p4c/mau/walk_power_graph.cpp
  backends/tofino/bf-p4c/midend/collect_pipelines.cpp
  backends/tofino/bf-p4c/midend/move_to_egress.cpp
  backends/tofino/bf-p4c/midend/parser_enforce_depth_req.cpp
  backends/tofino/bf-p4c/p4c-barefoot.cpp
  backends/tofino/bf-p4c/parde/allocate_parser_match_register.cpp
  backends/tofino/bf-p4c/parde/check_parser_multi_write.cpp
  backends/tofino/bf-p4c/parde/clot/allocate_clot.cpp
  backends/tofino/bf-p4c/parde/clot/clot_candidate.cpp
  backends/tofino/bf-p4c/parde/extract_parser.cpp
  backends/tofino/bf-p4c/parde/lower_parser.cpp
  backends/tofino/bf-p4c/parde/parser_dominator_builder.cpp
  backends/tofino/bf-p4c/parde/parser_info.h
  backends/tofino/bf-p4c/parde/phase0.cpp
  backends/tofino/bf-p4c/parde/resolve_negative_extract.h
  backends/tofino/bf-p4c/phv/add_initialization.cpp
  backends/tofino/bf-p4c/phv/analysis/header_mutex.cpp
  backends/tofino/bf-p4c/phv/analysis/header_mutex.h
  backends/tofino/bf-p4c/phv/phv_fields.cpp
  backends/tofino/bf-p4c/phv/phv_spec.cpp
  backends/tofino/bf-p4c/phv/pragma/pa_alias.cpp
  backends/tofino/bf-p4c/phv/pragma/pa_byte_pack.cpp
  backends/tofino/bf-p4c/phv/utils/utils.cpp
  backends/tofino/bf-p4c/phv/v2/copacker.cpp
Labels: core, tofino

#5002 Small TC fixes
  backends/tc/ebpfCodeGen.cpp
  backends/tc/runtime/pna.h
  backends/tc/tc.def
  testdata/p4tc_samples_outputs/set_entry_timer_example_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_04_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_05_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_06_parser.h
Labels: p4tc

#5005 Bump Compiler Version to 1.2.5.0.
  Version.txt
Labels: p4-spec

#5012 Remove some trivial leaks in codebase
  frontends/p4/def_use.cpp
  frontends/p4/def_use.h
  frontends/p4/moveDeclarations.cpp
  frontends/p4/moveDeclarations.h
  frontends/p4/parserControlFlow.cpp
  frontends/p4/removeParameters.cpp
  frontends/p4/removeReturns.cpp
  frontends/p4/setHeaders.cpp
  frontends/p4/setHeaders.h
  frontends/p4/sideEffects.cpp
  frontends/p4/simplifyParsers.cpp
  frontends/p4/specialize.cpp
  frontends/p4/specialize.h
  frontends/p4/structInitializers.cpp
  frontends/p4/typeChecking/bindVariables.cpp
  frontends/p4/typeChecking/bindVariables.h
  frontends/p4/typeChecking/typeCheckDecl.cpp
  frontends/p4/typeChecking/typeCheckExpr.cpp
  frontends/p4/typeChecking/typeChecker.cpp
  frontends/p4/typeChecking/typeUnification.cpp
  frontends/parsers/p4/p4parser.ypp
  ir/visitor.h
  midend/copyStructures.cpp
  midend/eliminateInvalidHeaders.cpp
  midend/expandEmit.cpp
  midend/flattenInterfaceStructs.h
  midend/flattenUnions.cpp
  midend/local_copyprop.cpp
  midend/local_copyprop.h
  midend/simplifyKey.cpp
Labels: core, run-sanitizer

#5016 minor fix to tofino cmake file
  backends/tofino/bf-p4c/CMakeLists.txt
Labels: tofino

#5017 Add Tofino to release.yml
  .github/release.yml
Labels: infrastructure

#5020 Fix modifyAllMatching visitor helper
  ir/visitor.h
Labels: core

#5022 Generate JSON actions and keys fields array even when they are empty
  backends/tc/introspection.cpp
  testdata/p4tc_samples_outputs/default_action_example_01.json
  testdata/p4tc_samples_outputs/multiple_tables_example_01.json
  testdata/p4tc_samples_outputs/multiple_tables_example_02.json
  testdata/p4tc_samples_outputs/noaction_example_02.json
  testdata/p4tc_samples_outputs/tc_type_annotation_example.json
Labels: p4tc

#5028 Fix Mac dependency installation.
  tools/install_mac_deps.sh
Labels: infrastructure

#5030 Inline some IR methods and constructors
  ir/base.def
  ir/expression.def
  ir/ir.def
  ir/type.cpp
  ir/type.def
  lib/error_reporter.h
  tools/ir-generator/ir-generator.ypp
  tools/ir-generator/irclass.cpp
Labels: core

#5007 Fix many Tofino warnings.
  backends/tofino/bf-p4c/arch/fromv1.0/stateful_alu.cpp
  backends/tofino/bf-p4c/arch/fromv1.0/v1_converters.h
  backends/tofino/bf-p4c/arch/psa/psa.cpp
  backends/tofino/bf-p4c/common/field_defuse.cpp
  backends/tofino/bf-p4c/control-plane/bfruntime_arch_handler.h
  backends/tofino/bf-p4c/logging/constrained_fields.h
  backends/tofino/bf-p4c/logging/resources_clot.h
  backends/tofino/bf-p4c/mau/action_analysis.cpp
  backends/tofino/bf-p4c/mau/action_format.cpp
  backends/tofino/bf-p4c/mau/determine_power_usage.cpp
  backends/tofino/bf-p4c/mau/gateway.cpp
  backends/tofino/bf-p4c/mau/instruction_selection.cpp
  backends/tofino/bf-p4c/mau/jbay_next_table.cpp
  backends/tofino/bf-p4c/mau/stateful_alu.cpp
  backends/tofino/bf-p4c/mau/table_placement.cpp
  backends/tofino/bf-p4c/mau/tofino/input_xbar.cpp
  backends/tofino/bf-p4c/mau/tofino/memories.cpp
  backends/tofino/bf-p4c/mau/tofino/memories.h
  backends/tofino/bf-p4c/mau/validate_actions.h
  backends/tofino/bf-p4c/mau/walk_power_graph.cpp
  backends/tofino/bf-p4c/midend/drop_packet_with_mirror_engine.cpp
  backends/tofino/bf-p4c/midend/move_to_egress.cpp
  backends/tofino/bf-p4c/midend/ping_pong_generation.h
  backends/tofino/bf-p4c/midend/table_mutex.h
  backends/tofino/bf-p4c/parde/check_parser_multi_write.cpp
  backends/tofino/bf-p4c/parde/check_parser_multi_write.h
  backends/tofino/bf-p4c/parde/lowered/compute_lowered_deparser_ir.cpp
  backends/tofino/bf-p4c/parde/marshal.h
  backends/tofino/bf-p4c/parde/parde_utils.h
  backends/tofino/bf-p4c/phv/action_phv_constraints.cpp
  backends/tofino/bf-p4c/phv/allocate_phv.cpp
  backends/tofino/bf-p4c/phv/allocate_phv.h
  backends/tofino/bf-p4c/phv/allocate_temps_and_finalize_liverange.cpp
  backends/tofino/bf-p4c/phv/analysis/header_mutex.h
  backends/tofino/bf-p4c/phv/collect_strided_headers.h
  backends/tofino/bf-p4c/phv/phv_fields.cpp
  backends/tofino/bf-p4c/phv/phv_fields.h
  backends/tofino/bf-p4c/phv/pragma/pa_byte_pack.cpp
  backends/tofino/bf-p4c/phv/v2/metadata_initialization.cpp
Labels: tofino
