Repository p4lang/p4c, pull requests merged in 2024-07, with the labels that each got.

#4769 Add a signature for the release bot for DCO support.
  .github/workflows/ci-auto-release.yml
Labels: infrastructure

#4771 Delete unused RemoveComplexExpressions pass.
  backends/common/removeComplexExpressions.cpp
  backends/common/removeComplexExpressions.h
Labels: core

#4684 P4Testgen logging cleanups.
  backends/p4tools/common/lib/logging.cpp
  backends/p4tools/common/lib/logging.h
  backends/p4tools/common/lib/util.h
  backends/p4tools/modules/testgen/lib/test_backend.cpp
Labels: p4tools

#4780 Improve cstring cache internals
  BUILD.bazel
  lib/cstring.cpp
  lib/cstring.h
  test/gtest/cstring.cpp
Labels: core

#4772 For-loop and for-in-loop support for P4Smith
  backends/p4tools/modules/smith/common/probabilities.h
  backends/p4tools/modules/smith/common/statements.cpp
  backends/p4tools/modules/smith/common/statements.h
  backends/p4tools/modules/smith/targets/generic/target.cpp
  backends/p4tools/modules/smith/targets/generic/target.h
  backends/p4tools/modules/smith/targets/generic/test/P4Tests.cmake
  backends/p4tools/modules/smith/targets/generic/test/smith_for_in_loop_test.cpp
  backends/p4tools/modules/smith/targets/generic/test/smith_for_loop_test.cpp
  backends/p4tools/modules/smith/util/util.cpp
Labels: p4tools

#4783 Fix loop unrolling bugs related to issue4739
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2MetadataXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufIrXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2STFXfail.cmake
  frontends/p4/simplifyDefUse.cpp
  midend/def_use.cpp
  midend/def_use.h
  midend/unrollLoops.cpp
  midend/unrollLoops.h
  testdata/p4_16_samples/issue4739.p4
  testdata/p4_16_samples_outputs/issue4739-first.p4
  testdata/p4_16_samples_outputs/issue4739-frontend.p4
  testdata/p4_16_samples_outputs/issue4739-midend.p4
  testdata/p4_16_samples_outputs/issue4739.p4
  testdata/p4_16_samples_outputs/issue4739.p4-stderr
  testdata/p4_16_samples_outputs/issue4739.p4.entries.txtpb
  testdata/p4_16_samples_outputs/issue4739.p4.p4info.txtpb
Labels: core

#4770 Move ProgramStructure out the BMv2 folder such that it can be used in other back ends.
  BUILD.bazel
  CMakeLists.txt
  backends/bmv2/CMakeLists.txt
  backends/bmv2/common/backend.h
  backends/bmv2/common/expression.h
  backends/bmv2/common/extern.h
  backends/bmv2/common/header.h
  backends/bmv2/common/helpers.h
  backends/bmv2/psa_switch/psaSwitch.cpp
  backends/bmv2/psa_switch/psaSwitch.h
  backends/bmv2/simple_switch/simpleSwitch.cpp
  backends/bmv2/simple_switch/simpleSwitch.h
  backends/common/CMakeLists.txt
  backends/common/metermap.cpp
  backends/common/metermap.h
  backends/common/programStructure.cpp
  backends/common/programStructure.h
  backends/common/psaProgramStructure.cpp
  backends/common/psaProgramStructure.h
  backends/ebpf/CMakeLists.txt
  backends/ebpf/ebpfBackend.cpp
  backends/ebpf/psa/backend.cpp
  backends/ebpf/psa/ebpfPsaGen.h
  backends/tc/CMakeLists.txt
  backends/tc/backend.cpp
  backends/tc/pnaProgramStructure.cpp
  backends/tc/pnaProgramStructure.h
Labels: bmv2, psa-bmv2, p4tc

#4788 Docs : Changelogs release update for v1.2.4.13
  CHANGELOG.md
Labels: documentation

#4781 Make HasTableApply a resolution context, so it could resolve declarations on its own if desired
  backends/dpdk/dpdkArch.cpp
  frontends/common/resolveReferences/resolveReferences.cpp
  frontends/p4/sideEffects.cpp
  frontends/p4/sideEffects.h
  midend/hsIndexSimplify.cpp
  midend/simplifyKey.cpp
  testdata/p4_16_samples/issue4775-2.p4
  testdata/p4_16_samples/issue4775.p4
  testdata/p4_16_samples_outputs/issue4775-2-first.p4
  testdata/p4_16_samples_outputs/issue4775-2-frontend.p4
  testdata/p4_16_samples_outputs/issue4775-2-midend.p4
  testdata/p4_16_samples_outputs/issue4775-2.p4
  testdata/p4_16_samples_outputs/issue4775-2.p4-stderr
  testdata/p4_16_samples_outputs/issue4775-first.p4
  testdata/p4_16_samples_outputs/issue4775-frontend.p4
  testdata/p4_16_samples_outputs/issue4775-midend.p4
  testdata/p4_16_samples_outputs/issue4775.p4
  testdata/p4_16_samples_outputs/issue4775.p4-stderr
Labels: core

#4790 P4C Options cleanup
  backends/p4tools/common/options.h
  frontends/common/options.cpp
  frontends/common/options.h
  frontends/common/parser_options.cpp
  frontends/common/parser_options.h
  lib/options.cpp
  lib/options.h
Labels: core, breaking-change

#4794 Fix broken CI runs because missing override in TC code.
  backends/tc/ebpfCodeGen.h
Labels: p4tc

#4726 [#4661] Do not unconditionally mark extern method calls as compile-time constants.
  frontends/p4/typeChecking/typeChecker.cpp
  testdata/p4_16_samples/issue4661_non_pure_extern_function_const_args.p4
  testdata/p4_16_samples/issue4661_pure_extern_function_const_args.p4
  testdata/p4_16_samples_outputs/issue4656_const_fold_generic_switch_label_expr.p4-stderr
  testdata/p4_16_samples_outputs/issue4661_non_pure_extern_function_const_args-first.p4
  testdata/p4_16_samples_outputs/issue4661_non_pure_extern_function_const_args-frontend.p4
  testdata/p4_16_samples_outputs/issue4661_non_pure_extern_function_const_args-midend.p4
  testdata/p4_16_samples_outputs/issue4661_non_pure_extern_function_const_args.p4
  testdata/p4_16_samples_outputs/issue4661_non_pure_extern_function_const_args.p4-stderr
  testdata/p4_16_samples_outputs/issue4661_pure_extern_function_const_args-first.p4
  testdata/p4_16_samples_outputs/issue4661_pure_extern_function_const_args-frontend.p4
  testdata/p4_16_samples_outputs/issue4661_pure_extern_function_const_args-midend.p4
  testdata/p4_16_samples_outputs/issue4661_pure_extern_function_const_args.p4
  testdata/p4_16_samples_outputs/issue4661_pure_extern_function_const_args.p4-stderr
Labels: core

#4774 Introduce string map class and switch to it
  backends/bmv2/common/JsonObjects.cpp
  backends/bmv2/common/action.cpp
  backends/bmv2/common/control.h
  backends/bmv2/common/deparser.cpp
  backends/bmv2/common/expression.cpp
  backends/bmv2/common/extern.cpp
  backends/bmv2/common/helpers.cpp
  backends/bmv2/common/parser.cpp
  backends/bmv2/common/sharedActionSelectorCheck.h
  backends/bmv2/psa_switch/psaSwitch.cpp
  backends/bmv2/psa_switch/psaSwitch.h
  backends/bmv2/simple_switch/simpleSwitch.cpp
  backends/bmv2/simple_switch/simpleSwitch.h
  backends/dpdk/control-plane/bfruntime_arch_handler.h
  backends/dpdk/control-plane/bfruntime_ext.cpp
  backends/dpdk/dpdkArch.cpp
  backends/dpdk/dpdkContext.cpp
  backends/dpdk/dpdkContext.h
  backends/dpdk/dpdkProgram.cpp
  backends/dpdk/spec.cpp
  backends/ebpf/psa/ebpfPsaTable.cpp
  backends/ebpf/psa/externs/ebpfPsaTableImplementation.cpp
  backends/graphs/graph_visitor.cpp
  backends/p4tools/common/lib/table_utils.cpp
  backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/small-step/reachability.cpp
  backends/p4tools/modules/testgen/targets/pna/shared_table_stepper.cpp
  backends/tc/introspection.cpp
  control-plane/bfruntime.cpp
  control-plane/bfruntime.h
  control-plane/p4RuntimeArchHandler.cpp
  control-plane/p4RuntimeArchStandard.h
  frontends/p4/checkNamedArgs.cpp
  frontends/p4/parameterSubstitution.h
  frontends/p4/typeChecking/typeChecker.cpp
  frontends/p4/typeChecking/typeUnification.cpp
  frontends/p4/validateParsedProgram.cpp
  ir/base.def
  ir/id.h
  ir/indexed_vector.h
  ir/ir.cpp
  ir/ir.def
  ir/json_loader.h
  ir/node.cpp
  ir/type.def
  ir/v1.def
  lib/json.cpp
  lib/json.h
  lib/string_map.h
  test/CMakeLists.txt
  test/gtest/json_test.cpp
  test/gtest/string_map.cpp
  tools/ir-generator/irclass.cpp
Labels: core, run-validation, run-sanitizer

#4799 Update the PINS programs.
  testdata/p4_16_samples/pins/README.md
  testdata/p4_16_samples/pins/pins_fabric.p4
  testdata/p4_16_samples/pins/pins_middleblock.p4
  testdata/p4_16_samples/pins/pins_wbb.p4
  testdata/p4_16_samples_outputs/pins/pins_fabric-first.p4
  testdata/p4_16_samples_outputs/pins/pins_fabric-frontend.p4
  testdata/p4_16_samples_outputs/pins/pins_fabric-midend.p4
  testdata/p4_16_samples_outputs/pins/pins_fabric.p4
  testdata/p4_16_samples_outputs/pins/pins_fabric.p4-stderr
  testdata/p4_16_samples_outputs/pins/pins_fabric.p4.p4info.txtpb
  testdata/p4_16_samples_outputs/pins/pins_middleblock-first.p4
  testdata/p4_16_samples_outputs/pins/pins_middleblock-frontend.p4
  testdata/p4_16_samples_outputs/pins/pins_middleblock-midend.p4
  testdata/p4_16_samples_outputs/pins/pins_middleblock.p4
  testdata/p4_16_samples_outputs/pins/pins_middleblock.p4-stderr
  testdata/p4_16_samples_outputs/pins/pins_middleblock.p4.p4info.txtpb
  testdata/p4_16_samples_outputs/pins/pins_wbb-first.p4
  testdata/p4_16_samples_outputs/pins/pins_wbb-frontend.p4
  testdata/p4_16_samples_outputs/pins/pins_wbb-midend.p4
  testdata/p4_16_samples_outputs/pins/pins_wbb.p4
  testdata/p4_16_samples_outputs/pins/pins_wbb.p4-stderr
  testdata/p4_16_samples_outputs/pins/pins_wbb.p4.p4info.txtpb
Labels: infrastructure

#4785 Make preprocess and getIncludePath const functions.
  backends/dpdk/options.cpp
  backends/dpdk/options.h
  backends/p4tools/modules/smith/options.cpp
  backends/p4tools/modules/smith/options.h
  backends/p4tools/modules/testgen/options.cpp
  backends/p4tools/modules/testgen/options.h
  frontends/common/parseInput.cpp
  frontends/common/parseInput.h
  frontends/common/parser_options.cpp
  frontends/common/parser_options.h
  frontends/p4/fromv1.0/programStructure.cpp
  lib/options.h
  test/gtest/midend_def_use.cpp
  test/gtest/p4runtime.cpp
  test/gtest/parser_unroll.cpp
Labels: core, breaking-change

#4801 Extend & fix FunctionInliner
  frontends/p4/actionsInlining.cpp
  frontends/p4/actionsInlining.h
  frontends/p4/commonInlining.h
  frontends/p4/functionsInlining.cpp
  frontends/p4/functionsInlining.h
  testdata/p4_16_samples/issue4796.p4
  testdata/p4_16_samples_outputs/issue4796-first.p4
  testdata/p4_16_samples_outputs/issue4796-frontend.p4
  testdata/p4_16_samples_outputs/issue4796-midend.p4
  testdata/p4_16_samples_outputs/issue4796.p4
  testdata/p4_16_samples_outputs/issue4796.p4-stderr
Labels: core

#4728 [P4Testgen] Refactor the P4Testgen extern implementation.
  backends/p4tools/modules/testgen/CMakeLists.txt
  backends/p4tools/modules/testgen/core/extern_info.h
  backends/p4tools/modules/testgen/core/externs.cpp
  backends/p4tools/modules/testgen/core/externs.h
  backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
  backends/p4tools/modules/testgen/core/small_step/expr_stepper.h
  backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
  backends/p4tools/modules/testgen/core/symbolic_executor/symbolic_executor.cpp
  backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.h
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2MetadataXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufIrXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2STFXfail.cmake
  backends/p4tools/modules/testgen/targets/ebpf/expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/ebpf/expr_stepper.h
  backends/p4tools/modules/testgen/targets/pna/dpdk/expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/pna/dpdk/expr_stepper.h
  backends/p4tools/modules/testgen/targets/pna/shared_expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/pna/shared_expr_stepper.h
  backends/p4tools/modules/testgen/targets/pna/test/PNAMetadataXfail.cmake
  backends/p4tools/modules/testgen/targets/pna/test/PNAPTFXfail.cmake
  backends/p4tools/modules/testgen/testgen.cpp
Labels: p4tools

#4814 [NFC] Split TypeInference
  frontends/CMakeLists.txt
  frontends/p4/typeChecking/constantTypeSubstitution.h
  frontends/p4/typeChecking/typeCheckDecl.cpp
  frontends/p4/typeChecking/typeCheckExpr.cpp
  frontends/p4/typeChecking/typeCheckStmt.cpp
  frontends/p4/typeChecking/typeCheckTypes.cpp
  frontends/p4/typeChecking/typeChecker.cpp
  frontends/p4/typeChecking/typeChecker.h
  frontends/p4/typeChecking/typeConstraints.h
Labels: core

#4812 Add test program to verify compile-time error if no type in for-in loop
  testdata/p4_16_errors/loop3-err.p4
  testdata/p4_16_errors_outputs/loop3-err.p4-stderr
Labels: infrastructure

#4797 Map written `LocationSet`s to program locations (`loc_t`) instead of `IR::Expression*`s
  frontends/p4/def_use.cpp
  frontends/p4/def_use.h
Labels: core

#4807 Update README.md instructions for running doxygen
  README.md
Labels: documentation

#4793 Fix: Links in Generated Documentation
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/doxygen/01_overview.md
  docs/doxygen/Doxymain.md
  docs/doxygen/doxygen.cfg
Labels: documentation

#4820 misc fixes/additions
  frontends/parsers/p4/p4parser.ypp
  ir/dbprint-p4.cpp
  ir/dbprint-stmt.cpp
  lib/hashvec.cpp
  lib/hvec_map.h
  lib/hvec_set.h
  midend/def_use.cpp
  midend/def_use.h
  test/CMakeLists.txt
  test/gtest/hvec_set.cpp
Labels: core

#4828 Minor Fix: links in P4Smith page
  CONTRIBUTING.md
  backends/p4tools/modules/smith/README.md
Labels: documentation

#4821 Remove multimap usage from `memoizeDeclsByName`
  frontends/common/resolveReferences/resolveReferences.cpp
  frontends/common/resolveReferences/resolveReferences.h
  lib/enumerator.h
Labels: core

#4817 Make don't care args action-local when used in actions
  frontends/p4/dontcareArgs.h
  test/CMakeLists.txt
  test/gtest/remove_dontcare_args_test.cpp
  test/gtest/strength_reduction.cpp
  testdata/p4_16_samples/localize_action_dont_care_args.p4
  testdata/p4_16_samples_outputs/localize_action_dont_care_args-first.p4
  testdata/p4_16_samples_outputs/localize_action_dont_care_args-frontend.p4
  testdata/p4_16_samples_outputs/localize_action_dont_care_args-midend.p4
  testdata/p4_16_samples_outputs/localize_action_dont_care_args.p4
  testdata/p4_16_samples_outputs/localize_action_dont_care_args.p4-stderr
Labels: core

#4706 [P4Testgen] Initialize the testgen targets when invoking the library API
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/benchmark.cpp
  backends/p4tools/modules/testgen/testgen.cpp
Labels: p4tools

#4837 Add string literal support in constant folding.
  frontends/common/constantFolding.cpp
Labels: core

#4836 Truncate shifts to the maximum constant bit-width in the constant folding pass.
  frontends/common/constantFolding.cpp
  testdata/p4_16_samples_outputs/constant_folding.p4-stderr
  testdata/p4_16_samples_outputs/gauntlet_various_ops-bmv2.p4-stderr
  testdata/p4_16_samples_outputs/issue3289.p4-stderr
Labels: core

#4833 [P4Testgen] Pass compiler options as argument, instead of getting them with static methods.
  backends/p4tools/common/compiler/compiler_target.cpp
  backends/p4tools/common/compiler/compiler_target.h
  backends/p4tools/common/options.h
  backends/p4tools/common/p4ctool.h
  backends/p4tools/modules/testgen/core/target.cpp
  backends/p4tools/modules/testgen/core/target.h
  backends/p4tools/modules/testgen/targets/bmv2/target.cpp
  backends/p4tools/modules/testgen/targets/bmv2/target.h
  backends/p4tools/modules/testgen/test/gtest_utils.cpp
  backends/p4tools/modules/testgen/testgen.cpp
Labels: p4tools

#4839 [P4Testgen] Hotfix for failing P4Testgen benchmark test.
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/benchmark.cpp
  backends/p4tools/modules/testgen/testgen.cpp
Labels: p4tools

#4789 [P4Testgen] Fix problems with the reachability pass.
  backends/p4tools/common/compiler/reachability.cpp
  backends/p4tools/common/compiler/reachability.h
  backends/p4tools/modules/smith/common/statements.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/small-step/reachability.cpp
  frontends/p4/callGraph.h
Labels: p4tools
