Repository p4lang/p4c, pull requests merged in 2024-09, with the labels that each got.

#4889 Add empty block for trailing case(s) with no code.
  frontends/p4/simplify.cpp
  testdata/p4_16_samples_outputs/cases-first.p4
  testdata/p4_16_samples_outputs/issue2617-first.p4
  testdata/p4_16_samples_outputs/issue3619-first.p4
  testdata/p4_16_samples_outputs/psa-switch-expression-without-default-first.p4
  testdata/p4_16_samples_outputs/psa-switch-expression-without-default-frontend.p4
  testdata/p4_16_samples_outputs/psa-switch-expression-without-default-midend.p4
Labels: core, run-validation

#4886 Silence -Wswitch-enum from bison generated file
  frontends/parsers/p4/p4parser.ypp
Labels: core, run-ubuntu18

#4829 Make type checking true read-only visitor
  frontends/CMakeLists.txt
  frontends/p4/methodInstance.cpp
  frontends/p4/staticAssert.h
  frontends/p4/typeChecking/constantTypeSubstitution.h
  frontends/p4/typeChecking/readOnlyTypeInference.cpp
  frontends/p4/typeChecking/typeCheckDecl.cpp
  frontends/p4/typeChecking/typeCheckExpr.cpp
  frontends/p4/typeChecking/typeCheckStmt.cpp
  frontends/p4/typeChecking/typeCheckTypes.cpp
  frontends/p4/typeChecking/typeChecker.cpp
  frontends/p4/typeChecking/typeChecker.h
  frontends/p4/typeChecking/typeInference.cpp
Labels: core, run-validation, run-sanitizer

#4875 Docs: Update Documentation Instructions
  docs/README.md
Labels: documentation

#4904 Reduce the number of memory allocations in def-use
  frontends/p4/def_use.cpp
  frontends/p4/def_use.h
  frontends/p4/simplifyDefUse.cpp
  lib/flat_map.h
  test/CMakeLists.txt
  test/gtest/flat_map.cpp
Labels: core, run-validation, run-sanitizer

#4905 Added "inst_type" field in introspection.json.
  backends/tc/backend.cpp
  backends/tc/backend.h
  backends/tc/introspection.cpp
  backends/tc/introspection.h
  backends/tc/tc.def
  testdata/p4tc_samples_outputs/direct_counter_example.json
  testdata/p4tc_samples_outputs/direct_meter.json
  testdata/p4tc_samples_outputs/direct_meter_color.json
  testdata/p4tc_samples_outputs/indirect_counter_01_example.json
  testdata/p4tc_samples_outputs/meter.json
  testdata/p4tc_samples_outputs/meter.template
  testdata/p4tc_samples_outputs/meter_color.json
Labels: p4tc, run-validation

#4902 Split the `start` state more conservatively when a parser contains decl initializers
  frontends/p4/moveDeclarations.cpp
  frontends/p4/moveDeclarations.h
  testdata/p4_16_samples/issue4901_new_start_with_no_start_loopback.p4
  testdata/p4_16_samples/issue4901_new_start_with_start_state_loopback.p4
  testdata/p4_16_samples/issue4901_new_start_with_start_state_loopback2.p4
  testdata/p4_16_samples_outputs/default-frontend.p4
  testdata/p4_16_samples_outputs/fabric_20190420/fabric-frontend.p4
  testdata/p4_16_samples_outputs/initializers-frontend.p4
  testdata/p4_16_samples_outputs/issue1538-frontend.p4
  testdata/p4_16_samples_outputs/issue2314-frontend.p4
  testdata/p4_16_samples_outputs/issue281-frontend.p4
  testdata/p4_16_samples_outputs/issue2957-frontend.p4
  testdata/p4_16_samples_outputs/issue361-bmv2-frontend.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_no_start_loopback-first.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_no_start_loopback-frontend.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_no_start_loopback-midend.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_no_start_loopback.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_no_start_loopback.p4-stderr
  testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback-first.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback-frontend.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback-midend.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback.p4-stderr
  testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback2-first.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback2-frontend.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback2-midend.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback2.p4
  testdata/p4_16_samples_outputs/issue4901_new_start_with_start_state_loopback2.p4-stderr
  testdata/p4_16_samples_outputs/parser-conditional-frontend.p4
  testdata/p4_16_samples_outputs/parser-conditional-midend.p4
Labels: core

#4915 Add missed include
  lib/flat_map.h
Labels: core

#4910 Only process `IR::Path`s inside of `IR::ParserState` contexts in `MoveInitializers`
  frontends/p4/moveDeclarations.cpp
Labels: core, run-sanitizer

#4898 Factor common base ExternCall for ExternMethod/ExternFunction
  frontends/p4/methodInstance.h
Labels: core

#4900 [#4883] Remove unused actions whose `@name` name starts with "__"
  frontends/p4/unusedDeclarations.cpp
  testdata/p4_16_errors_outputs/structure-valued-expr-errs-1.p4-stderr
  testdata/p4_16_samples/issue4883_dup_has_returned_decl.p4
  testdata/p4_16_samples/issue4883_dup_has_returned_decl2.p4
  testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl-first.p4
  testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl-frontend.p4
  testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl-midend.p4
  testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl.p4
  testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl.p4-stderr
  testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl2-first.p4
  testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl2-frontend.p4
  testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl2-midend.p4
  testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl2.p4
  testdata/p4_16_samples_outputs/issue4883_dup_has_returned_decl2.p4-stderr
Labels: core

#4894 Allow `--Wdisable` to take precedence over `--Werror` for warning messages
  frontends/common/parser_options.h
  frontends/p4/fromv1.0/programStructure.cpp
  lib/compile_context.cpp
  lib/compile_context.h
  lib/error.h
  lib/error_catalog.cpp
  lib/error_catalog.h
  lib/error_reporter.h
  midend/parserUnroll.cpp
Labels: core

#4921 Remove the workaround that was required for MacOS CI installation.
  .github/workflows/ci-test-mac.yml
Labels: infrastructure

#4897 Allow keywords to be used as annotation names.
  frontends/parsers/p4/p4parser.ypp
Labels: core

#4877 Avoid copying out/inout args when inlining functions
  frontends/p4/functionsInlining.cpp
  frontends/p4/functionsInlining.h
  frontends/p4/parameterSubstitution.h
  testdata/p4_16_samples_outputs/issue2345-2-frontend.p4
  testdata/p4_16_samples_outputs/issue2345-2-midend.p4
Labels: core, run-validation

#4899 Allow extending ToP4, clean its constructors
  frontends/common/parser_options.cpp
  frontends/common/parser_options.h
  frontends/p4/frontend.cpp
  frontends/p4/toP4/toP4.h
Labels: core, breaking-change

#4925 Clean up the P4-14 dependent code.
  backends/bmv2/common/controlFlowGraph.cpp
  backends/bmv2/common/extern.cpp
  backends/bmv2/common/helpers.h
  backends/bmv2/common/lower.cpp
  backends/bmv2/common/parser.cpp
  backends/bmv2/pna_nic/midend.cpp
  backends/bmv2/portable_common/midend.cpp
  backends/bmv2/psa_switch/midend.cpp
  backends/bmv2/simple_switch/midend.cpp
  backends/bmv2/simple_switch/simpleSwitch.cpp
  backends/bmv2/simple_switch/simpleSwitch.h
  backends/dpdk/midend.cpp
  backends/p4fmt/p4formatter.cpp
  backends/p4test/midend.cpp
  control-plane/p4RuntimeArchHandler.cpp
  control-plane/p4RuntimeArchStandard.cpp
  control-plane/p4RuntimeArchStandard.h
  control-plane/p4RuntimeSerializer.cpp
  frontends/CMakeLists.txt
  frontends/common/parseInput.cpp
  frontends/common/parseInput.h
  frontends/p4-14/fromv1.0/converters.cpp
  frontends/p4-14/fromv1.0/converters.h
  frontends/p4-14/fromv1.0/programStructure.cpp
  frontends/p4-14/fromv1.0/programStructure.h
  frontends/p4-14/fromv1.0/v1model.cpp
  frontends/p4-14/fromv1.0/v1model.h
  frontends/p4-14/ir-v1.def
  frontends/p4-14/v1.cpp
  frontends/p4/frontend.cpp
  frontends/p4/getV1ModelVersion.h
  frontends/p4/modelInstances.cpp
  frontends/p4/toP4/toP4.cpp
  ir/CMakeLists.txt
  ir/v1.def
  midend/removeComplexExpressions.cpp
  test/gtest/midend_pass.cpp
Labels: core

#4927 Fix Type_Indexed::at
  ir/type.def
Labels: core

#4924 Make --top4 matching case-insensitive.
  frontends/common/parser_options.cpp
Labels: core

#4787 [P4Testgen] Unify compiler options and tool options. Ensure options context is always initialized correctly.
  backends/p4tools/BUILD.bazel
  backends/p4tools/common/compiler/compiler_target.cpp
  backends/p4tools/common/compiler/compiler_target.h
  backends/p4tools/common/compiler/context.h
  backends/p4tools/common/core/target.cpp
  backends/p4tools/common/core/target.h
  backends/p4tools/common/options.cpp
  backends/p4tools/common/options.h
  backends/p4tools/common/p4ctool.h
  backends/p4tools/modules/smith/core/target.cpp
  backends/p4tools/modules/smith/core/target.h
  backends/p4tools/modules/smith/options.cpp
  backends/p4tools/modules/smith/options.h
  backends/p4tools/modules/smith/smith.cpp
  backends/p4tools/modules/testgen/core/target.cpp
  backends/p4tools/modules/testgen/core/target.h
  backends/p4tools/modules/testgen/options.cpp
  backends/p4tools/modules/testgen/options.h
  backends/p4tools/modules/testgen/targets/bmv2/test/gtest_utils.h
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/api_test.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/benchmark.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/control_plane_filter_test.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/output_option_test.cpp
  backends/p4tools/modules/testgen/test/gtest_utils.cpp
  backends/p4tools/modules/testgen/test/gtest_utils.h
  backends/p4tools/modules/testgen/testgen.cpp
  backends/p4tools/modules/testgen/testgen.h
Labels: p4tools
