Repository p4lang/p4c, pull requests merged in 2024-03, with the labels that each got.

#4473 Use abseil maps even more
  BUILD.bazel
  CMakeLists.txt
  backends/bmv2/CMakeLists.txt
  backends/dpdk/CMakeLists.txt
  backends/graphs/CMakeLists.txt
  backends/p4tools/common/CMakeLists.txt
  frontends/CMakeLists.txt
  frontends/common/resolveReferences/referenceMap.cpp
  frontends/common/resolveReferences/referenceMap.h
  frontends/common/resolveReferences/resolveReferences.h
  frontends/p4/def_use.cpp
  frontends/p4/def_use.h
  frontends/p4/simplifyDefUse.cpp
  frontends/p4/typeMap.cpp
  frontends/p4/typeMap.h
  midend/CMakeLists.txt
Labels: core, run-validation

#4475 [P4Testgen] Add a rudimentary P4Testgen benchmark with via GTest.
  backends/p4tools/modules/testgen/lib/test_backend.cpp
  backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
  backends/p4tools/modules/testgen/targets/bmv2/test/testgen_api/benchmark.cpp
  backends/p4tools/modules/testgen/testgen.cpp
  test/gtest/helpers.cpp
  test/gtest/helpers.h
Labels: testgen

#4322 [P4Testgen] Make more functions of the P4Tools Z3 API accessible.
  backends/p4tools/common/core/z3_solver.cpp
  backends/p4tools/common/core/z3_solver.h
Labels: testgen

#4495 Move CI Mac and Fedora tests to separate test runs.
  .github/workflows/ci-lint.yaml
  .github/workflows/ci-p4tools.yml
  .github/workflows/ci-ptf.yml
  .github/workflows/ci-static-build-test.yml
  .github/workflows/ci-test-debian.yml
  .github/workflows/ci-test-fedora.yml
  .github/workflows/ci-test-mac.yml
  .github/workflows/ci-test.yml
  .github/workflows/ci-ubuntu-18-nightly.yml
  .github/workflows/ci-ubuntu-20-sanitizer-nightly.yml
Labels: test-infrastructure

#4482 Replace boost string algorithms with their abseil counterparts
  backends/p4tools/modules/testgen/test/small-step/util.cpp
  control-plane/CMakeLists.txt
  control-plane/p4RuntimeSymbolTable.cpp
  frontends/CMakeLists.txt
  frontends/p4/typeChecking/typeConstraints.cpp
  frontends/p4/typeChecking/typeConstraints.h
  frontends/parsers/parserDriver.cpp
  frontends/parsers/v1/v1lexer.ll
  frontends/parsers/v1/v1lexer_internal.hpp
  ir/namemap.h
  lib/README.md
  lib/cstring.h
  lib/source_file.cpp
  lib/source_file.h
  lib/stringify.cpp
  lib/stringify.h
  lib/stringref.h
  test/gtest/complex_bitwise.cpp
  test/gtest/diagnostics.cpp
  test/gtest/p4runtime.cpp
  test/gtest/path_test.cpp
  tools/ir-generator/ir-generator.ypp
Labels: core

#4492 Build P4Testgen on MacOS.
  .github/workflows/ci-test-mac.yml
Labels: testgen, test-infrastructure

#4496 HalfOpenRange/ClosedRange classes
  ir/CMakeLists.txt
  ir/bitrange.cpp
  lib/CMakeLists.txt
  lib/bitrange.cpp
  lib/bitrange.h
  test/CMakeLists.txt
  test/gtest/bitrange.cpp
Labels: core

#4515 Update formatters (clang-format, isort, black)
  backends/bmv2/common/parser.cpp
  backends/bmv2/psa_switch/psaSwitch.cpp
  backends/dpdk/spec.cpp
  backends/ebpf/target.h
  backends/p4tools/common/version.cpp
  backends/p4tools/modules/testgen/lib/execution_state.cpp
  backends/p4tools/modules/testgen/main.cpp
  backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test_spec.cpp
  backends/p4tools/modules/testgen/targets/pna/shared_program_info.cpp
  backends/ubpf/target.h
  frontends/common/constantFolding.cpp
  ir/v1.cpp
  ir/visitor.cpp
  lib/algorithm.h
  lib/hashvec.cpp
  lib/json.cpp
  midend/convertEnums.cpp
  requirements.txt
  tools/ir-generator/methods.cpp
Labels: test-infrastructure

#4504 [Docs] Added tools to directory structure
  docs/README.md
Labels: documentation

#4521 YAML formatting from Redhead YAML language server.
  .github/workflows/ci-auto-release.yml
  .github/workflows/ci-bazel.yml
  .github/workflows/ci-container-image.yml
  .github/workflows/ci-lint.yaml
  .github/workflows/ci-p4tools.yml
  .github/workflows/ci-ptf-kernels-weekly.yml
  .github/workflows/ci-ptf.yml
  .github/workflows/ci-release.yml
  .github/workflows/ci-static-build-test.yml
  .github/workflows/ci-test-debian.yml
  .github/workflows/ci-test-fedora.yml
  .github/workflows/ci-test-mac.yml
Labels: test-infrastructure

#4506 [docs] subdirectories and description for control plane
  docs/README.md
Labels: documentation

#4452 Allow annotations on functions
  frontends/parsers/p4/p4parser.ypp
  ir/ir.def
Labels: p4-spec

#4529 tc_may_override annotation implementation
  backends/tc/backend.cpp
  backends/tc/ebpfCodeGen.cpp
  backends/tc/ebpfCodeGen.h
  backends/tc/tc.def
  backends/tc/tcAnnotations.cpp
  backends/tc/tcAnnotations.h
  testdata/p4tc_samples/tc_may_override_example_01.p4
  testdata/p4tc_samples/tc_may_override_example_02.p4
  testdata/p4tc_samples/tc_may_override_example_03.p4
  testdata/p4tc_samples/tc_may_override_example_04.p4
  testdata/p4tc_samples/tc_may_override_example_05.p4
  testdata/p4tc_samples/tc_may_override_example_06.p4
  testdata/p4tc_samples_outputs/tc_may_override_example_01.json
  testdata/p4tc_samples_outputs/tc_may_override_example_01.p4-stderr
  testdata/p4tc_samples_outputs/tc_may_override_example_01.template
  testdata/p4tc_samples_outputs/tc_may_override_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_01_parser.c
  testdata/p4tc_samples_outputs/tc_may_override_example_01_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_02.json
  testdata/p4tc_samples_outputs/tc_may_override_example_02.p4-stderr
  testdata/p4tc_samples_outputs/tc_may_override_example_02.template
  testdata/p4tc_samples_outputs/tc_may_override_example_02_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_02_parser.c
  testdata/p4tc_samples_outputs/tc_may_override_example_02_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_03.json
  testdata/p4tc_samples_outputs/tc_may_override_example_03.p4-stderr
  testdata/p4tc_samples_outputs/tc_may_override_example_03.template
  testdata/p4tc_samples_outputs/tc_may_override_example_03_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_03_parser.c
  testdata/p4tc_samples_outputs/tc_may_override_example_03_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_04.json
  testdata/p4tc_samples_outputs/tc_may_override_example_04.p4-stderr
  testdata/p4tc_samples_outputs/tc_may_override_example_04.template
  testdata/p4tc_samples_outputs/tc_may_override_example_04_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_04_parser.c
  testdata/p4tc_samples_outputs/tc_may_override_example_04_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_05.json
  testdata/p4tc_samples_outputs/tc_may_override_example_05.p4-stderr
  testdata/p4tc_samples_outputs/tc_may_override_example_05.template
  testdata/p4tc_samples_outputs/tc_may_override_example_05_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_05_parser.c
  testdata/p4tc_samples_outputs/tc_may_override_example_05_parser.h
  testdata/p4tc_samples_outputs/tc_may_override_example_06.json
  testdata/p4tc_samples_outputs/tc_may_override_example_06.p4-stderr
  testdata/p4tc_samples_outputs/tc_may_override_example_06.template
  testdata/p4tc_samples_outputs/tc_may_override_example_06_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_06_parser.c
  testdata/p4tc_samples_outputs/tc_may_override_example_06_parser.h
Labels: p4tc

#4530 Extend parser to allow parentheses in lvalues
  frontends/parsers/p4/p4parser.ypp
  testdata/p4_16_samples/lvalue-parens.p4
  testdata/p4_16_samples_outputs/lvalue-parens-first.p4
  testdata/p4_16_samples_outputs/lvalue-parens-frontend.p4
  testdata/p4_16_samples_outputs/lvalue-parens-midend.p4
  testdata/p4_16_samples_outputs/lvalue-parens.p4
  testdata/p4_16_samples_outputs/lvalue-parens.p4-stderr
Labels: p4-spec

#4491 Add ninja as a default build system for some runners.
  .github/workflows/ci-lint.yaml
  .github/workflows/ci-p4tools.yml
  .github/workflows/ci-ptf.yml
  .github/workflows/ci-static-build-test.yml
  .github/workflows/ci-test-debian.yml
  .github/workflows/ci-test-fedora.yml
  .github/workflows/ci-test-mac.yml
  backends/bmv2/CMakeLists.txt
  bootstrap.sh
  tools/ci-build.sh
  tools/install_fedora_deps.sh
  tools/install_mac_deps.sh
Labels: test-infrastructure

#4516 [docs] Sync Directory structure of P4tools
  backends/p4tools/README.md
Labels: documentation

#4520 Clean up P4Tools and control-plane linking.
  backends/p4tools/cmake/common.cmake
  backends/p4tools/common/CMakeLists.txt
  backends/p4tools/common/control_plane/CMakeLists.txt
  backends/p4tools/modules/testgen/CMakeLists.txt
  backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
  control-plane/CMakeLists.txt
  frontends/CMakeLists.txt
  midend/CMakeLists.txt
Labels: enhancement, control-plane, testgen, run-ubuntu18

#4306 [P4Testgen] Fix append and prepend invocation.
  backends/p4tools/common/lib/trace_event_types.cpp
  backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
Labels: testgen

#4541 Remove obsolete `output_to_genfiles = True`.
  bazel/bison.bzl
Labels: dependencies

#4531 [documentation] Add hyperlinks to the actual directory in the README file.
  backends/dpdk/README.md
  backends/tc/README.md
  backends/ubpf/README.md
Labels: documentation

#4511 Use Abseil system includes
  backends/p4tools/modules/testgen/test/small-step/util.cpp
  bazel/abseil.patch
  bazel/p4c_deps.bzl
  control-plane/p4RuntimeSymbolTable.cpp
  frontends/common/resolveReferences/referenceMap.h
  frontends/common/resolveReferences/resolveReferences.h
  frontends/p4/def_use.h
  frontends/p4/simplifyDefUse.cpp
  frontends/p4/typeChecking/typeConstraints.cpp
  frontends/p4/typeMap.h
  ir/visitor.cpp
  test/gtest/complex_bitwise.cpp
  test/gtest/diagnostics.cpp
  test/gtest/p4runtime.cpp
Labels: core

#4528 Add policy controlling RemoveUnusedDeclarations
  backends/bmv2/psa_switch/psaSwitch.cpp
  backends/bmv2/simple_switch/simpleSwitch.cpp
  backends/dpdk/backend.cpp
  frontends/p4/actionsInlining.h
  frontends/p4/frontend.cpp
  frontends/p4/frontend.h
  frontends/p4/functionsInlining.h
  frontends/p4/inlining.h
  frontends/p4/localizeActions.h
  frontends/p4/redundantParsers.h
  frontends/p4/specialize.cpp
  frontends/p4/specialize.h
  frontends/p4/unusedDeclarations.cpp
  frontends/p4/unusedDeclarations.h
  midend/flattenUnions.h
Labels: core

#4547 Fix a warning on missing override in def use class.
  midend/def_use.h
Labels: core, run-sanitizer

#4526 Move the network hashes implementation from Bmv2 testgen to lib/
  backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
  backends/p4tools/modules/testgen/targets/bmv2/concolic.cpp
  backends/p4tools/modules/testgen/targets/bmv2/concolic.h
  backends/p4tools/modules/testgen/targets/bmv2/contrib/bmv2_hash/calculations.h
  lib/CMakeLists.txt
  lib/nethash.cpp
  lib/nethash.h
  test/CMakeLists.txt
  test/gtest/nethash.cpp
Labels: testgen, core, run-validation

#4550 Add 2 more CRC checksum variants to lib/nethash
  lib/nethash.cpp
  lib/nethash.h
  test/gtest/nethash.cpp
Labels: core

#4513 Refactor Util::Enumerator
  backends/p4tools/common/compiler/reachability.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test/small-step/reachability.cpp
  frontends/common/resolveReferences/resolveReferences.cpp
  frontends/p4/parameterSubstitution.h
  ir/dbprint-p4.cpp
  ir/indexed_vector.h
  ir/ir.cpp
  ir/namemap.h
  ir/vector.h
  lib/enumerator.h
  lib/iterator_range.h
  lib/map.h
  midend/flattenInterfaceStructs.h
  test/gtest/enumerator_test.cpp
  tools/ir-generator/irclass.cpp
  tools/ir-generator/methods.cpp
Labels: core

#4555 Corrected version in README.md
  README.md
Labels: documentation

#4399 Implict cast fix
  frontends/p4/typeChecking/typeChecker.cpp
  frontends/p4/typeChecking/typeConstraints.cpp
  frontends/p4/typeChecking/typeConstraints.h
  testdata/p4_16_errors/serEnumImplCast.p4
  testdata/p4_16_errors_outputs/serEnumImplCast.p4
  testdata/p4_16_errors_outputs/serEnumImplCast.p4-stderr
  testdata/p4_16_samples/serEnumImplCast.p4
  testdata/p4_16_samples_outputs/serEnumImplCast-first.p4
  testdata/p4_16_samples_outputs/serEnumImplCast-frontend.p4
  testdata/p4_16_samples_outputs/serEnumImplCast-midend.p4
  testdata/p4_16_samples_outputs/serEnumImplCast.p4
  testdata/p4_16_samples_outputs/serEnumImplCast.p4-stderr
Labels: core, p4-spec

#4546 [P4Testgen] Clean up the direct extern map implementation for BMv2.
  backends/p4tools/modules/testgen/targets/bmv2/bmv2.cpp
  backends/p4tools/modules/testgen/targets/bmv2/map_direct_externs.cpp
  backends/p4tools/modules/testgen/targets/bmv2/map_direct_externs.h
  backends/p4tools/modules/testgen/targets/bmv2/program_info.cpp
  lib/bitrange.h
Labels: testgen

#4556 Suppress Abseil warnings.
  CMakeLists.txt
  cmake/Abseil.cmake
  cmake/Linters.cmake
  cmake/P4CUtils.cmake
Labels: dependencies, run-ubuntu18, run-sanitizer

#4560 [P4Testgen] Add a missing nullopt check.
  backends/p4tools/modules/testgen/testgen.cpp
Labels: testgen

#4559 Add p4tc_filter_fields in add_entry
  backends/tc/ebpfCodeGen.cpp
  backends/tc/runtime/pna.h
  testdata/p4tc_samples_outputs/add_entry_1_example_control_blocks.c
  testdata/p4tc_samples_outputs/add_entry_example_control_blocks.c
Labels: p4tc

#4561 Added default action code for tc backend
  backends/tc/ebpfCodeGen.cpp
  backends/tc/ebpfCodeGen.h
  testdata/p4tc_samples_outputs/tc_may_override_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_04_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_05_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_06_control_blocks.c
Labels: p4tc

#4569 Fix broken Debian CI test badge in the README. Add Fedora and MacOS CI badge.
  README.md
Labels: documentation

#4565 Fix Resource links in Doxygen documentation.
  docs/doxygen/01_overview.md
Labels: documentation
