Repository p4lang/p4c, pull requests merged in 2024-10, with the labels that each got.

#4930 [P4Tools] Clean up use of ::P4 prefix for errors, warnings, and logs.
  backends/p4tools/common/compiler/compiler_target.cpp
  backends/p4tools/common/lib/format_int.cpp
  backends/p4tools/common/lib/logging.cpp
  backends/p4tools/common/options.cpp
  backends/p4tools/modules/smith/options.cpp
  backends/p4tools/modules/smith/smith.cpp
  backends/p4tools/modules/testgen/core/small_step/small_step.cpp
  backends/p4tools/modules/testgen/core/symbolic_executor/depth_first.cpp
  backends/p4tools/modules/testgen/core/symbolic_executor/greedy_node_cov.cpp
  backends/p4tools/modules/testgen/core/symbolic_executor/random_backtrack.cpp
  backends/p4tools/modules/testgen/core/symbolic_executor/selected_branches.cpp
  backends/p4tools/modules/testgen/core/symbolic_executor/symbolic_executor.cpp
  backends/p4tools/modules/testgen/lib/final_state.cpp
  backends/p4tools/modules/testgen/lib/logging.cpp
  backends/p4tools/modules/testgen/options.cpp
  backends/p4tools/modules/testgen/targets/bmv2/cmd_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/map_direct_externs.cpp
  backends/p4tools/modules/testgen/targets/bmv2/p4_asserts_parser.cpp
  backends/p4tools/modules/testgen/targets/bmv2/p4runtime_translation.cpp
  backends/p4tools/modules/testgen/targets/bmv2/table_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/target.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
  backends/p4tools/modules/testgen/targets/ebpf/expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/ebpf/table_stepper.cpp
  backends/p4tools/modules/testgen/targets/ebpf/target.cpp
  backends/p4tools/modules/testgen/targets/ebpf/test_backend.cpp
  backends/p4tools/modules/testgen/targets/pna/shared_table_stepper.cpp
  backends/p4tools/modules/testgen/targets/pna/test_backend.cpp
  backends/p4tools/modules/testgen/testgen.cpp
Labels: p4tools

#4917 Support for [lsb+:width] slices
  backends/p4tools/common/lib/symbolic_env.cpp
  backends/p4tools/modules/smith/common/statements.cpp
  backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
  backends/p4tools/modules/testgen/core/small_step/expr_stepper.h
  frontends/common/constantFolding.cpp
  frontends/common/constantFolding.h
  frontends/p4-14/fromv1.0/converters.cpp
  frontends/p4/alias.h
  frontends/p4/def_use.cpp
  frontends/p4/def_use.h
  frontends/p4/inlining.cpp
  frontends/p4/sideEffects.cpp
  frontends/p4/simplifyDefUse.cpp
  frontends/p4/strengthReduction.cpp
  frontends/p4/strengthReduction.h
  frontends/p4/toP4/toP4.cpp
  frontends/p4/toP4/toP4.h
  frontends/p4/typeChecking/readOnlyTypeInference.cpp
  frontends/p4/typeChecking/typeCheckExpr.cpp
  frontends/p4/typeChecking/typeChecker.h
  frontends/p4/typeChecking/typeInference.cpp
  frontends/parsers/p4/p4parser.ypp
  ir/dbprint-expression.cpp
  ir/expression.cpp
  ir/expression.def
  ir/write_context.cpp
  midend/def_use.cpp
  midend/global_copyprop.cpp
  midend/local_copyprop.cpp
  testdata/p4_16_samples/forloop5a.p4
  testdata/p4_16_samples_outputs/forloop5a-first.p4
  testdata/p4_16_samples_outputs/forloop5a-frontend.p4
  testdata/p4_16_samples_outputs/forloop5a-midend.p4
  testdata/p4_16_samples_outputs/forloop5a.p4
  testdata/p4_16_samples_outputs/forloop5a.p4-stderr
Labels: p4-spec

#4937 Fix parser symbolic interpreter to evaluate StringLiteral
  midend/interpreter.cpp
  midend/interpreter.h
  test/gtest/parser_unroll.cpp
  testdata/p4_16_samples/issue4932.p4
  testdata/p4_16_samples_outputs/issue4932-first.p4
  testdata/p4_16_samples_outputs/issue4932-frontend.p4
  testdata/p4_16_samples_outputs/issue4932-midend.p4
  testdata/p4_16_samples_outputs/issue4932.p4
  testdata/p4_16_samples_outputs/issue4932.p4-stderr
Labels: bug, core

#4939 Remove reference map from another set of midend passes
  backends/bmv2/common/lower.cpp
  backends/bmv2/common/lower.h
  backends/bmv2/pna_nic/midend.cpp
  backends/bmv2/pna_nic/pnaNic.cpp
  backends/bmv2/psa_switch/midend.cpp
  backends/bmv2/psa_switch/psaSwitch.cpp
  backends/bmv2/simple_switch/midend.cpp
  backends/bmv2/simple_switch/simpleSwitch.cpp
  backends/dpdk/backend.cpp
  backends/dpdk/dpdkArch.h
  backends/dpdk/dpdkCheckExternInvocation.h
  backends/dpdk/midend.cpp
  backends/ebpf/midend.cpp
  backends/p4test/midend.cpp
  backends/p4tools/common/compiler/midend.cpp
  backends/tc/midend.cpp
  backends/ubpf/midend.cpp
  frontends/common/constantFolding.h
  frontends/p4-14/fromv1.0/converters.cpp
  frontends/p4-14/fromv1.0/programStructure.cpp
  frontends/p4/evaluator/substituteParameters.h
  frontends/p4/optimizeExpressions.h
  frontends/p4/parserControlFlow.h
  frontends/p4/removeParameters.h
  frontends/p4/removeReturns.h
  frontends/p4/specializeGenericTypes.cpp
  frontends/p4/specializeGenericTypes.h
  frontends/parsers/parserDriver.cpp
  midend/checkExternInvocationCommon.h
  midend/convertErrors.h
  midend/copyStructures.cpp
  midend/copyStructures.h
  midend/eliminateInvalidHeaders.h
  midend/eliminateSwitch.cpp
  midend/eliminateSwitch.h
  midend/eliminateTuples.h
  midend/expandLookahead.h
  midend/flattenInterfaceStructs.cpp
  midend/flattenInterfaceStructs.h
  midend/flattenLogMsg.h
  midend/has_side_effects.h
  midend/hsIndexSimplify.cpp
  midend/hsIndexSimplify.h
  midend/local_copyprop.cpp
  midend/local_copyprop.h
  midend/nestedStructs.cpp
  midend/nestedStructs.h
  midend/predication.h
  midend/removeComplexExpressions.cpp
  midend/removeComplexExpressions.h
  midend/removeExits.cpp
  midend/removeSelectBooleans.h
  midend/simplifyKey.h
  midend/simplifySelectList.h
  test/gtest/constant_folding.cpp
  test/gtest/frontend_test.cpp
  test/gtest/midend_pass.cpp
Labels: core, run-validation, run-sanitizer, breaking-change

#4946 [P4Testgen] Move newline stripping from trace to TestFramework
  backends/p4tools/common/lib/trace_event_types.cpp
  backends/p4tools/modules/testgen/lib/test_framework.h
  backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
Labels: p4tools

#4943 Add Vector::dbprint
  ir/vector.h
Labels: core, run-validation

#4941 extend type checking to mark extern function call that returns enum a…
  frontends/p4/typeChecking/typeCheckExpr.cpp
  testdata/p4_16_samples/hashext3.p4
  testdata/p4_16_samples_outputs/hashext3-first.p4
  testdata/p4_16_samples_outputs/hashext3-frontend.p4
  testdata/p4_16_samples_outputs/hashext3.p4
  testdata/p4_16_samples_outputs/hashext3.p4-stderr
  testdata/p4_16_samples_outputs/issue4661_pure_extern_function_const_args.p4-stderr
Labels: core

#4950 Ignore brew dependency installation to fix breakages on MacOS CI.
  tools/install_mac_deps.sh
Labels: infrastructure

#4938 Reorder subdirectory additions in CMakeLists.txt
  CMakeLists.txt
Labels: core

#4949 Change tc template define
  backends/tc/tc.def
  testdata/p4tc_samples_outputs/add_entry_1_example.template
  testdata/p4tc_samples_outputs/add_entry_3_example.template
  testdata/p4tc_samples_outputs/add_entry_example.template
  testdata/p4tc_samples_outputs/calculator.template
  testdata/p4tc_samples_outputs/checksum.template
  testdata/p4tc_samples_outputs/const_entries_range_mask.template
  testdata/p4tc_samples_outputs/default_action_example.template
  testdata/p4tc_samples_outputs/default_action_example_01.template
  testdata/p4tc_samples_outputs/default_action_with_param.template
  testdata/p4tc_samples_outputs/default_action_with_param_01.template
  testdata/p4tc_samples_outputs/default_hit_const_example.template
  testdata/p4tc_samples_outputs/digest.template
  testdata/p4tc_samples_outputs/digest_01.template
  testdata/p4tc_samples_outputs/direct_counter_example.template
  testdata/p4tc_samples_outputs/direct_meter.template
  testdata/p4tc_samples_outputs/direct_meter_color.template
  testdata/p4tc_samples_outputs/drop_packet_example.template
  testdata/p4tc_samples_outputs/global_action_example_01.template
  testdata/p4tc_samples_outputs/global_action_example_02.template
  testdata/p4tc_samples_outputs/hash1.template
  testdata/p4tc_samples_outputs/indirect_counter_01_example.template
  testdata/p4tc_samples_outputs/internetchecksum_01.template
  testdata/p4tc_samples_outputs/ipip.template
  testdata/p4tc_samples_outputs/is_host_port.template
  testdata/p4tc_samples_outputs/is_net_port.template
  testdata/p4tc_samples_outputs/matchtype.template
  testdata/p4tc_samples_outputs/meter.template
  testdata/p4tc_samples_outputs/meter_color.template
  testdata/p4tc_samples_outputs/mix_matchtype_example.template
  testdata/p4tc_samples_outputs/multiple_tables_example_01.template
  testdata/p4tc_samples_outputs/multiple_tables_example_02.template
  testdata/p4tc_samples_outputs/name_annotation_example.template
  testdata/p4tc_samples_outputs/no_table_example.template
  testdata/p4tc_samples_outputs/noaction_example_01.template
  testdata/p4tc_samples_outputs/noaction_example_02.template
  testdata/p4tc_samples_outputs/nummask_annotation_example.template
  testdata/p4tc_samples_outputs/send_to_port_example.template
  testdata/p4tc_samples_outputs/set_entry_timer_example.template
  testdata/p4tc_samples_outputs/simple_exact_example.template
  testdata/p4tc_samples_outputs/simple_extern_example.template
  testdata/p4tc_samples_outputs/simple_lpm_example.template
  testdata/p4tc_samples_outputs/simple_ternary_example.template
  testdata/p4tc_samples_outputs/size_param_example.template
  testdata/p4tc_samples_outputs/tc_may_override_example_01.template
  testdata/p4tc_samples_outputs/tc_may_override_example_02.template
  testdata/p4tc_samples_outputs/tc_may_override_example_03.template
  testdata/p4tc_samples_outputs/tc_may_override_example_04.template
  testdata/p4tc_samples_outputs/tc_may_override_example_05.template
  testdata/p4tc_samples_outputs/tc_may_override_example_06.template
  testdata/p4tc_samples_outputs/tc_may_override_example_07.template
  testdata/p4tc_samples_outputs/tc_may_override_example_08.template
  testdata/p4tc_samples_outputs/tc_may_override_example_09.template
  testdata/p4tc_samples_outputs/tc_type_annotation_example.template
  testdata/p4tc_samples_outputs/test_ipv6_example.template
Labels: p4tc

#4953 Add LOGGING_FEATURE macro
  lib/log.h
Labels: core

#4940 Add utilities for running modifications inside nested IR nodes
  backends/p4tools/modules/testgen/core/small_step/abstract_stepper.cpp
  backends/p4tools/modules/testgen/core/small_step/expr_stepper.cpp
  backends/p4tools/modules/testgen/core/small_step/extern_stepper.cpp
  ir/CMakeLists.txt
  ir/ir-traversal-internal.h
  ir/ir-traversal.h
  test/CMakeLists.txt
  test/gtest/ir-traversal-test.cpp
Labels: core

#4948 Do not print confusing warning when a parser state contains an assignment to an l-value slice
  midend/interpreter.cpp
  testdata/p4_16_samples/parser-unroll-uninitialized-slice-read.p4
  testdata/p4_16_samples/parser-unroll-uninitialized-slice-write.p4
  testdata/p4_16_samples_outputs/parser-unroll-uninitialized-slice-read-first.p4
  testdata/p4_16_samples_outputs/parser-unroll-uninitialized-slice-read-frontend.p4
  testdata/p4_16_samples_outputs/parser-unroll-uninitialized-slice-read-midend.p4
  testdata/p4_16_samples_outputs/parser-unroll-uninitialized-slice-read.p4
  testdata/p4_16_samples_outputs/parser-unroll-uninitialized-slice-read.p4-stderr
  testdata/p4_16_samples_outputs/parser-unroll-uninitialized-slice-write-first.p4
  testdata/p4_16_samples_outputs/parser-unroll-uninitialized-slice-write-frontend.p4
  testdata/p4_16_samples_outputs/parser-unroll-uninitialized-slice-write-midend.p4
  testdata/p4_16_samples_outputs/parser-unroll-uninitialized-slice-write.p4
  testdata/p4_16_samples_outputs/parser-unroll-uninitialized-slice-write.p4-stderr
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-uninitialized-slice-read-first.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-uninitialized-slice-read-frontend.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-uninitialized-slice-read-midend.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-uninitialized-slice-read.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-uninitialized-slice-read.p4-stderr
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-uninitialized-slice-write-first.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-uninitialized-slice-write-frontend.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-uninitialized-slice-write-midend.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-uninitialized-slice-write.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-uninitialized-slice-write.p4-stderr
Labels: core

#4960 Fix a recently introduced typo
  docs/README.md
Labels: documentation

#4957 Fix Fedora CI build.
  .github/workflows/ci-test-fedora.yml
  tools/install_fedora_deps.sh
Labels: run-ubuntu18, infrastructure

#4954 Make number of masks default to 1 for exact tables
  backends/tc/tc.def
  backends/tc/tc_defines.h
  testdata/p4tc_samples_outputs/add_entry_1_example.template
  testdata/p4tc_samples_outputs/add_entry_3_example.template
  testdata/p4tc_samples_outputs/add_entry_example.template
  testdata/p4tc_samples_outputs/calculator.template
  testdata/p4tc_samples_outputs/checksum.template
  testdata/p4tc_samples_outputs/const_entries_range_mask.template
  testdata/p4tc_samples_outputs/default_action_example.template
  testdata/p4tc_samples_outputs/default_action_example_01.template
  testdata/p4tc_samples_outputs/default_action_with_param.template
  testdata/p4tc_samples_outputs/default_action_with_param_01.template
  testdata/p4tc_samples_outputs/default_hit_const_example.template
  testdata/p4tc_samples_outputs/digest.template
  testdata/p4tc_samples_outputs/digest_01.template
  testdata/p4tc_samples_outputs/direct_counter_example.template
  testdata/p4tc_samples_outputs/direct_meter.template
  testdata/p4tc_samples_outputs/direct_meter_color.template
  testdata/p4tc_samples_outputs/drop_packet_example.template
  testdata/p4tc_samples_outputs/global_action_example_01.template
  testdata/p4tc_samples_outputs/global_action_example_02.template
  testdata/p4tc_samples_outputs/indirect_counter_01_example.template
  testdata/p4tc_samples_outputs/internetchecksum_01.template
  testdata/p4tc_samples_outputs/ipip.template
  testdata/p4tc_samples_outputs/is_host_port.template
  testdata/p4tc_samples_outputs/is_net_port.template
  testdata/p4tc_samples_outputs/matchtype.template
  testdata/p4tc_samples_outputs/meter.template
  testdata/p4tc_samples_outputs/meter_color.template
  testdata/p4tc_samples_outputs/mix_matchtype_example.template
  testdata/p4tc_samples_outputs/multiple_tables_example_01.template
  testdata/p4tc_samples_outputs/multiple_tables_example_02.template
  testdata/p4tc_samples_outputs/name_annotation_example.template
  testdata/p4tc_samples_outputs/noaction_example_01.template
  testdata/p4tc_samples_outputs/noaction_example_02.template
  testdata/p4tc_samples_outputs/nummask_annotation_example.template
  testdata/p4tc_samples_outputs/send_to_port_example.template
  testdata/p4tc_samples_outputs/set_entry_timer_example.template
  testdata/p4tc_samples_outputs/simple_exact_example.template
  testdata/p4tc_samples_outputs/simple_extern_example.template
  testdata/p4tc_samples_outputs/simple_lpm_example.template
  testdata/p4tc_samples_outputs/simple_ternary_example.template
  testdata/p4tc_samples_outputs/size_param_example.template
  testdata/p4tc_samples_outputs/skb_meta.p4-stderr
  testdata/p4tc_samples_outputs/tc_may_override_example_01.template
  testdata/p4tc_samples_outputs/tc_may_override_example_02.template
  testdata/p4tc_samples_outputs/tc_may_override_example_03.template
  testdata/p4tc_samples_outputs/tc_may_override_example_04.template
  testdata/p4tc_samples_outputs/tc_may_override_example_05.template
  testdata/p4tc_samples_outputs/tc_may_override_example_06.template
  testdata/p4tc_samples_outputs/tc_may_override_example_07.template
  testdata/p4tc_samples_outputs/tc_may_override_example_08.template
  testdata/p4tc_samples_outputs/tc_may_override_example_09.template
  testdata/p4tc_samples_outputs/tc_type_annotation_example.template
  testdata/p4tc_samples_outputs/test_ipv6_example.template
Labels: p4tc

#4967 wrap <64bit types properly in loop unrolling
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2MetadataXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2PTFXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2ProtobufIrXfail.cmake
  backends/p4tools/modules/testgen/targets/bmv2/test/BMV2STFXfail.cmake
  midend/unrollLoops.cpp
  testdata/p4_16_samples/loop-3-clause-tricky2.p4
  testdata/p4_16_samples_outputs/loop-3-clause-tricky2-first.p4
  testdata/p4_16_samples_outputs/loop-3-clause-tricky2-frontend.p4
  testdata/p4_16_samples_outputs/loop-3-clause-tricky2-midend.p4
  testdata/p4_16_samples_outputs/loop-3-clause-tricky2.p4
  testdata/p4_16_samples_outputs/loop-3-clause-tricky2.p4-stderr
  testdata/p4_16_samples_outputs/loop-3-clause-tricky2.p4.entries.txtpb
  testdata/p4_16_samples_outputs/loop-3-clause-tricky2.p4.p4info.txtpb
Labels: core

#4955 Handle pna_main_parser_input_metadata_t fields in the tc backend's parser
  backends/tc/ebpfCodeGen.cpp
  backends/tc/ebpfCodeGen.h
  p4include/tc/pna.p4
  testdata/p4tc_samples/digest_parser_meta.p4
  testdata/p4tc_samples_outputs/digest_parser_meta.json
  testdata/p4tc_samples_outputs/digest_parser_meta.p4-stderr
  testdata/p4tc_samples_outputs/digest_parser_meta.template
  testdata/p4tc_samples_outputs/digest_parser_meta_control_blocks.c
  testdata/p4tc_samples_outputs/digest_parser_meta_parser.c
  testdata/p4tc_samples_outputs/digest_parser_meta_parser.h
Labels: p4tc

#4968 Add a couple of missing ENABLE_* flags to README
  README.md
Labels: documentation

#4976 bump up grpcio version to fix mac m1 ci issue
  requirements.txt
Labels: infrastructure

#4977 Require the driver binary as a test input.
  tools/driver/CMakeLists.txt
  tools/driver/test_scripts/driver_inputs_test_1___one_bad_pathname.bash
  tools/driver/test_scripts/driver_inputs_test_2___two_bad_pathnames.bash
  tools/driver/test_scripts/driver_inputs_test_3___three_bad_pathnames.bash
  tools/driver/test_scripts/driver_inputs_test_4___two_good_pathnames___check_for_no_misleading_error_messages.bash
  tools/driver/test_scripts/driver_inputs_test___shared_code.bash
Labels: infrastructure

#4952 Support for 128 bit bitwise operation
  backends/dpdk/CMakeLists.txt
  backends/dpdk/DpdkXfail.cmake
  backends/dpdk/dbprint-dpdk.cpp
  backends/dpdk/dpdk.def
  backends/dpdk/dpdkArch.h
  backends/dpdk/dpdkHelpers.cpp
  backends/dpdk/dpdkHelpers.h
  backends/dpdk/dpdkProgram.cpp
  backends/dpdk/dpdkProgramStructure.h
  backends/dpdk/spec.cpp
  testdata/p4_16_dpdk_errors/dash-pipeline-pna-dpdk.p4
  testdata/p4_16_dpdk_errors_outputs/dash-pipeline-pna-dpdk.p4-error
  testdata/p4_16_dpdk_errors_outputs/dash-pipeline-pna-dpdk.p4.bfrt.json
  testdata/p4_16_samples/pna-ipv6-actions.p4
  testdata/p4_16_samples_outputs/pna-ipv6-actions-first.p4
  testdata/p4_16_samples_outputs/pna-ipv6-actions-frontend.p4
  testdata/p4_16_samples_outputs/pna-ipv6-actions-midend.p4
  testdata/p4_16_samples_outputs/pna-ipv6-actions.p4
  testdata/p4_16_samples_outputs/pna-ipv6-actions.p4-error
  testdata/p4_16_samples_outputs/pna-ipv6-actions.p4-stderr
  testdata/p4_16_samples_outputs/pna-ipv6-actions.p4.bfrt.json
  testdata/p4_16_samples_outputs/pna-ipv6-actions.p4.spec
  testdata/p4_16_samples_outputs/psa-dpdk-128bitCast.p4.spec
Labels: dpdk

#4845 [P4fmt]: attaching comments to IR Nodes
  backends/p4fmt/CMakeLists.txt
  backends/p4fmt/attach.cpp
  backends/p4fmt/attach.h
  backends/p4fmt/p4fmt.cpp
  frontends/parsers/parserDriver.cpp
  frontends/parsers/parserDriver.h
  lib/source_file.cpp
  lib/source_file.h
Labels: p4fmt

#4984 Remove Tofino-specific Python packages from requirements.txt
  .github/workflows/disabled/ci-dpdk-ptf-p4testgen-tests.yml
  requirements.txt
  tools/ci-build.sh
Labels: run-ubuntu18, infrastructure

#4981 Clean up BMv2's run-stf-test script and integrate it with testutils
  backends/bmv2/CMakeLists.txt
  backends/bmv2/bmv2stf.py
  backends/bmv2/run-bmv2-test.py
  backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
  pyproject.toml
  tools/stf/stf_parser.py
  tools/testutils.py
Labels: bmv2, run-ubuntu18, infrastructure

#4834 [P4Testgen] Run typechecking after front and mid end.
  backends/p4tools/common/compiler/compiler_target.cpp
  backends/p4tools/common/compiler/midend.cpp
  backends/p4tools/common/compiler/midend.h
Labels: p4tools

#4986 Fix Fedora build and fix CMake warnings on versions greater than CMake 3.24.
  backends/ebpf/CMakeLists.txt
  cmake/Abseil.cmake
  cmake/GoogleTest.cmake
  cmake/Protobuf.cmake
  requirements.txt
  tools/install_fedora_deps.sh
Labels: run-ubuntu18, infrastructure

#4697 Build Z3 from source instead of downloading precompiled binaries.
  backends/p4tools/common/CMakeLists.txt
  backends/p4tools/common/core/z3_solver.cpp
  backends/p4tools/common/core/z3_solver.h
  backends/tofino/CMakeLists.txt
  backends/tofino/bf-p4c/CMakeLists.txt
  cmake/Z3.cmake
  cmake/z3.patch
Labels: p4tools, infrastructure

#4989 Fix warning about delete not matching new
  backends/p4tools/p4tools.def
  ir/type.def
Labels: core
