Repository p4lang/p4c, pull requests merged in 2024-04, with the labels that each got.

#4584 Update rules_boost which pulled in the compromised xz dependency.
  bazel/p4c_deps.bzl
Labels: dependencies

#4573 [docs] Add Comment Style Guide
  docs/README.md
Labels: documentation

#4554 doc: backends: Add Doxygen-style documentation for BMV2 JSONObjects
  backends/bmv2/common/JsonObjects.cpp
  backends/bmv2/common/JsonObjects.h
Labels: documentation

#4566 Handle Arithmetic operations for fields which are in network order
  backends/ebpf/codeGen.cpp
  backends/ebpf/codeGen.h
  backends/ebpf/ebpfParser.cpp
  backends/ebpf/target.h
  backends/tc/backend.cpp
  backends/tc/ebpfCodeGen.cpp
  backends/tc/ebpfCodeGen.h
  testdata/p4tc_samples/add_entry_1_example.p4
  testdata/p4tc_samples/ipip.p4
  testdata/p4tc_samples/simple_exact_example.p4
  testdata/p4tc_samples_outputs/add_entry_1_example.json
  testdata/p4tc_samples_outputs/add_entry_1_example.template
  testdata/p4tc_samples_outputs/add_entry_1_example_control_blocks.c
  testdata/p4tc_samples_outputs/add_entry_1_example_parser.c
  testdata/p4tc_samples_outputs/ipip_control_blocks.c
  testdata/p4tc_samples_outputs/ipip_parser.c
  testdata/p4tc_samples_outputs/matchtype_control_blocks.c
  testdata/p4tc_samples_outputs/mix_matchtype_example_control_blocks.c
  testdata/p4tc_samples_outputs/nummask_annotation_example_control_blocks.c
  testdata/p4tc_samples_outputs/simple_exact_example.json
  testdata/p4tc_samples_outputs/simple_exact_example_control_blocks.c
  testdata/p4tc_samples_outputs/simple_exact_example_parser.c
  testdata/p4tc_samples_outputs/simple_lpm_example_control_blocks.c
Labels: p4tc, run-sanitizer

#4581 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#4594 Revert using Abseil system includes.
  backends/p4tools/modules/testgen/test/small-step/util.cpp
  bazel/abseil.patch
  bazel/p4c_deps.bzl
  control-plane/p4RuntimeSymbolTable.cpp
  frontends/common/resolveReferences/referenceMap.h
  frontends/common/resolveReferences/resolveReferences.h
  frontends/p4/def_use.h
  frontends/p4/simplifyDefUse.cpp
  frontends/p4/typeChecking/typeConstraints.cpp
  frontends/p4/typeMap.h
  ir/visitor.cpp
  lib/bitrange.h
  test/gtest/complex_bitwise.cpp
  test/gtest/diagnostics.cpp
  test/gtest/p4runtime.cpp
Labels: dependencies

#4577 [DOCS][Refactor] Replace direct links with word links
  README.md
  backends/bmv2/README.md
  backends/dpdk/README.md
  backends/ebpf/README.md
  backends/p4tools/README.md
  backends/tc/README.md
  docs/IR.md
  docs/README.md
  testdata/p4_16_samples/dash/README.md
  testdata/p4_16_samples/omec/README.md
  testdata/p4_16_samples/pins/README.md
  tools/README.md
Labels: documentation

#4580 Improve & Move "How to contribute" section to Top level readme
  README.md
  docs/README.md
Labels: documentation

#4590 [Docs] Add Table of Content
  README.md
Labels: documentation

#4601 Do not swallow the output when checking for existence of the static binary in the PTF eBPF test.
  backends/ebpf/runtime/kernel.mk
Labels: ebpf-psa, test-infrastructure

#4600 restore missing parentheses
  lib/map.h
  test/CMakeLists.txt
  test/gtest/map.cpp
Labels: core

#4539 Make the tree cloner also clone Member(TypeNameExpression) to ensure the result is a DAG
  backends/bmv2/psa_switch/psaSwitch.cpp
  backends/bmv2/simple_switch/simpleSwitch.cpp
  frontends/p4/cloner.h
  frontends/p4/localizeActions.cpp
  frontends/p4/sideEffects.cpp
  frontends/p4/simplifyDefUse.h
  midend/predication.cpp
  testdata/p4_16_samples/issue4500.p4
  testdata/p4_16_samples_outputs/issue4500-first.p4
  testdata/p4_16_samples_outputs/issue4500-frontend.p4
  testdata/p4_16_samples_outputs/issue4500-midend.p4
  testdata/p4_16_samples_outputs/issue4500.p4
  testdata/p4_16_samples_outputs/issue4500.p4-stderr
Labels: core

#4593 Update the DASH programs.
  testdata/p4_16_samples/dash/dash-pipeline-pna-dpdk.p4
  testdata/p4_16_samples/dash/dash-pipeline-v1model-bmv2.p4
  testdata/p4_16_samples_outputs/dash/dash-pipeline-pna-dpdk-first.p4
  testdata/p4_16_samples_outputs/dash/dash-pipeline-pna-dpdk-frontend.p4
  testdata/p4_16_samples_outputs/dash/dash-pipeline-pna-dpdk-midend.p4
  testdata/p4_16_samples_outputs/dash/dash-pipeline-pna-dpdk.p4
  testdata/p4_16_samples_outputs/dash/dash-pipeline-pna-dpdk.p4-stderr
  testdata/p4_16_samples_outputs/dash/dash-pipeline-v1model-bmv2-first.p4
  testdata/p4_16_samples_outputs/dash/dash-pipeline-v1model-bmv2-frontend.p4
  testdata/p4_16_samples_outputs/dash/dash-pipeline-v1model-bmv2-midend.p4
  testdata/p4_16_samples_outputs/dash/dash-pipeline-v1model-bmv2.p4
  testdata/p4_16_samples_outputs/dash/dash-pipeline-v1model-bmv2.p4-stderr
  testdata/p4_16_samples_outputs/dash/dash-pipeline-v1model-bmv2.p4.entries.txt
  testdata/p4_16_samples_outputs/dash/dash-pipeline-v1model-bmv2.p4.p4info.txt
  testdata/p4_16_samples_outputs/dash/dash-pipeline-v1model-bmv2.p4.p4info.txtpb
Labels: test-infrastructure

#4597 Add option to build with dynamic libc and c++, but static other dependencies; change static option name
  .github/workflows/ci-static-build-test.yml
  CMakeLists.txt
  Dockerfile
  tools/ci-build.sh
  tools/ci-check-static.sh
  tools/debian-build/packaging.conf
Labels: enhancement, core, run-static

#4608 Inspector: clear the done flag when revisiting node
  ir/visitor.cpp
  test/CMakeLists.txt
  test/gtest/visitor.cpp
Labels: core

#4616 [Docs] Improve formatting for consistency
  README.md
Labels: documentation

#4613 Miscellaneous cleanups for P4Testgen.
  backends/p4tools/common/core/z3_solver.cpp
  backends/p4tools/common/lib/gen_eq.cpp
  backends/p4tools/modules/testgen/core/program_info.cpp
  backends/p4tools/modules/testgen/core/small_step/abstract_stepper.cpp
  backends/p4tools/modules/testgen/targets/bmv2/expr_stepper.cpp
  backends/p4tools/modules/testgen/targets/ebpf/constants.cpp
  backends/p4tools/modules/testgen/targets/pna/constants.cpp
  backends/p4tools/modules/testgen/test/z3-solver/constraints.cpp
  test/gtest/visitor.cpp
Labels: testgen

#4621 Fix missing override in the visitor test compilation unit.
  test/gtest/visitor.cpp
Labels: core

#4588 Force black to use the pytoml file as configuration.
  cmake/Linters.cmake
Labels: test-infrastructure

#4619 Update the Commenting Style in the DPDK backend
  backends/dpdk/backend.cpp
  backends/dpdk/constants.h
  backends/dpdk/control-plane/bfruntime_arch_handler.h
  backends/dpdk/control-plane/bfruntime_ext.h
  backends/dpdk/dpdkArch.cpp
  backends/dpdk/dpdkAsmOpt.cpp
  backends/dpdk/dpdkAsmOpt.h
  backends/dpdk/dpdkCheckExternInvocation.h
  backends/dpdk/dpdkContext.cpp
  backends/dpdk/dpdkContext.h
  backends/dpdk/dpdkHelpers.cpp
  backends/dpdk/dpdkHelpers.h
  backends/dpdk/dpdkMetadata.cpp
  backends/dpdk/dpdkMetadata.h
  backends/dpdk/dpdkProgram.cpp
  backends/dpdk/dpdkProgram.h
  backends/dpdk/dpdkProgramStructure.cpp
  backends/dpdk/dpdkProgramStructure.h
  backends/dpdk/dpdkUtils.cpp
  backends/dpdk/dpdkUtils.h
  backends/dpdk/midend.cpp
  backends/dpdk/midend.h
  backends/dpdk/options.h
  backends/dpdk/printUtils.h
  backends/dpdk/spec.cpp
  docs/README.md
Labels: documentation

#4620 [Docs] Non-Breaking change of "p4c" to "P4C"
  CONTRIBUTING.md
  README.md
  backends/graphs/README.md
  backends/p4tools/modules/testgen/targets/bmv2/test/README.md
  bazel/example/README.md
  docs/CodingStandardPhilosophy.md
  docs/Eclipse-readme.md
  docs/README.md
Labels: documentation

#4628 Use `IR::Annotation::nameAnnotation` everywhere instead of hard-coding `@name` annotation name
  frontends/p4/def_use.h
  frontends/p4/simplifyParsers.cpp
Labels: core

#4609 Ensure we take compiler-provided declaration of posix_memalign
  lib/gc.cpp
Labels: core, run-sanitizer

#4626 Call PassManager's debug hook even after a failing pass
  frontends/common/parser_options.cpp
  ir/pass_manager.cpp
  ir/pass_manager.h
Labels: core

#4624 Update ebpf comment format
  backends/ebpf/codeGen.cpp
  backends/ebpf/codeGen.h
  backends/ebpf/ebpfControl.h
  backends/ebpf/ebpfDeparser.h
  backends/ebpf/ebpfModel.h
  backends/ebpf/ebpfObject.h
  backends/ebpf/ebpfOptions.h
  backends/ebpf/ebpfParser.h
  backends/ebpf/ebpfProgram.h
  backends/ebpf/ebpfTable.cpp
  backends/ebpf/ebpfTable.h
  backends/ebpf/ebpfType.h
  backends/ebpf/lower.h
  backends/ebpf/midend.h
  backends/ebpf/psa/backend.h
  backends/ebpf/psa/ebpfPipeline.cpp
  backends/ebpf/psa/ebpfPipeline.h
  backends/ebpf/psa/ebpfPsaControl.cpp
  backends/ebpf/psa/ebpfPsaControl.h
  backends/ebpf/psa/ebpfPsaDeparser.cpp
  backends/ebpf/psa/ebpfPsaGen.cpp
  backends/ebpf/psa/ebpfPsaGen.h
  backends/ebpf/psa/ebpfPsaTable.cpp
  backends/ebpf/psa/ebpfPsaTable.h
  backends/ebpf/psa/externs/ebpfPsaChecksum.cpp
  backends/ebpf/psa/externs/ebpfPsaDigest.cpp
  backends/ebpf/psa/externs/ebpfPsaDigest.h
  backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
  backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.h
  backends/ebpf/psa/externs/ebpfPsaRegister.cpp
  backends/ebpf/psa/externs/ebpfPsaRegister.h
  backends/ebpf/psa/externs/ebpfPsaTableImplementation.cpp
  backends/ebpf/psa/externs/ebpfPsaTableImplementation.h
  backends/ebpf/psa/xdpHelpProgram.h
  backends/ebpf/runtime/ebpf_common.h
  backends/ebpf/runtime/ebpf_kernel.h
  backends/ebpf/runtime/ebpf_map.c
  backends/ebpf/runtime/ebpf_map.h
  backends/ebpf/runtime/ebpf_registry.c
  backends/ebpf/runtime/ebpf_registry.h
  backends/ebpf/runtime/ebpf_runtime.c
  backends/ebpf/runtime/ebpf_runtime_kernel.h
  backends/ebpf/runtime/ebpf_runtime_test.c
  backends/ebpf/runtime/ebpf_runtime_test.h
  backends/ebpf/runtime/ebpf_test.h
  backends/ebpf/runtime/pcap_util.h
  backends/ebpf/runtime/psa.h
  backends/ebpf/target.h
Labels: documentation

#4627 [#4625] Prune `MethodCallStatement`s if child `MethodCallExpression` resolves to a compile-time constant.
  frontends/p4/typeChecking/typeChecker.cpp
  frontends/p4/typeChecking/typeChecker.h
  testdata/p4_16_samples/issue4625_remove_compile_time_bool_methodcall_of_mcs.p4
  testdata/p4_16_samples/issue4625_remove_compile_time_const_methodcall_of_mcs.p4
  testdata/p4_16_samples_outputs/issue4625_remove_compile_time_bool_methodcall_of_mcs-first.p4
  testdata/p4_16_samples_outputs/issue4625_remove_compile_time_bool_methodcall_of_mcs-frontend.p4
  testdata/p4_16_samples_outputs/issue4625_remove_compile_time_bool_methodcall_of_mcs-midend.p4
  testdata/p4_16_samples_outputs/issue4625_remove_compile_time_bool_methodcall_of_mcs.p4
  testdata/p4_16_samples_outputs/issue4625_remove_compile_time_bool_methodcall_of_mcs.p4-stderr
  testdata/p4_16_samples_outputs/issue4625_remove_compile_time_const_methodcall_of_mcs-first.p4
  testdata/p4_16_samples_outputs/issue4625_remove_compile_time_const_methodcall_of_mcs-frontend.p4
  testdata/p4_16_samples_outputs/issue4625_remove_compile_time_const_methodcall_of_mcs-midend.p4
  testdata/p4_16_samples_outputs/issue4625_remove_compile_time_const_methodcall_of_mcs.p4
  testdata/p4_16_samples_outputs/issue4625_remove_compile_time_const_methodcall_of_mcs.p4-stderr
Labels: core

#4632 [Docs] capitalize "GCC" acronym in docs and comment
  .github/workflows/ci-ubuntu-18-nightly.yml
  README.md
  backends/bmv2/common/helpers.h
  backends/ebpf/runtime/contrib/uthash.h
  control-plane/p4RuntimeArchStandard.h
  docs/README.md
  ir/vector.h
  ir/visitor.cpp
  lib/log.cpp
  lib/rtti.h
  test/gtest/bitrange.cpp
  test/gtest/bitvec_test.cpp
  testdata/p4_16_samples/op_bin.p4
  tools/cpplint.py
Labels: documentation

#4630 Update graphs comment formatting.
  backends/graphs/controls.cpp
  backends/graphs/controls.h
  backends/graphs/graph_visitor.cpp
  backends/graphs/graph_visitor.h
  backends/graphs/graphs.h
  backends/graphs/parsers.cpp
Labels: documentation

#4622 P4TC - Emit 'NoAction' in table actions list in template file
  backends/tc/backend.cpp
  backends/tc/backend.h
  backends/tc/tc.def
  testdata/p4tc_samples/default_action_example_01.p4
  testdata/p4tc_samples_outputs/default_action_example_01.json
  testdata/p4tc_samples_outputs/default_action_example_01.p4-stderr
  testdata/p4tc_samples_outputs/default_action_example_01.template
  testdata/p4tc_samples_outputs/default_action_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/default_action_example_01_parser.c
  testdata/p4tc_samples_outputs/default_action_example_01_parser.h
  testdata/p4tc_samples_outputs/multiple_tables_example_01.template
  testdata/p4tc_samples_outputs/multiple_tables_example_02.template
  testdata/p4tc_samples_outputs/noaction_example_01.template
  testdata/p4tc_samples_outputs/noaction_example_02.template
  testdata/p4tc_samples_outputs/tc_type_annotation_example.template
  testdata/p4tc_samples_outputs/test_ipv6_example.template
Labels: p4tc

#4633 allow disabling of subtraction transform
  frontends/p4/frontend.cpp
  frontends/p4/frontend.h
  frontends/p4/strengthReduction.cpp
  frontends/p4/strengthReduction.h
  test/CMakeLists.txt
  test/gtest/strength_reduction.cpp
Labels: core

#4629 Contribute DiagnosticCountInPassHook
  backends/p4test/p4test.cpp
  ir/CMakeLists.txt
  ir/pass_utils.cpp
  ir/pass_utils.h
Labels: core

#4642 Update MacOS brew version.
  tools/install_mac_deps.sh
Labels: core

#4618 Fix: Outdated links
  backends/ebpf/README.md
  backends/ebpf/runtime/ebpf_kernel.h
  backends/p4tools/modules/testgen/README.md
  testdata/p4_14_samples/p414-special-ops-2-bmv2.stf
  testdata/p4_14_samples/p414-special-ops-3-bmv2.stf
  testdata/p4_14_samples/p414-special-ops.stf
  testdata/p4_16_samples/fabric_20190420/fabric.p4
  tools/cpplint.py
Labels: documentation

#4638 Add -mbmi flag to Abseil for GCC versions greater than 14.
  cmake/Abseil.cmake
Labels: run-ubuntu18, run-sanitizer, run-static
