Repository p4lang/p4c, pull requests merged in 2024-06, with the labels that each got.

#4686 Refactor error_helper and around
  BUILD.bazel
  backends/p4tools/common/core/z3_solver.cpp
  backends/p4tools/modules/testgen/lib/exceptions.h
  frontends/p4/typeChecking/typeChecker.h
  ir/expression.def
  ir/visitor.h
  lib/backtrace_exception.h
  lib/big_int_fwd.h
  lib/bug_helper.h
  lib/error.h
  lib/error_helper.h
  lib/error_message.h
  lib/error_reporter.h
  lib/log.h
  lib/options.h
  lib/source_file.cpp
  lib/source_file.h
  lib/stringify.cpp
  lib/stringify.h
  midend/def_use.cpp
  test/gtest/source_file_test.cpp
  tools/ir-generator/ir-generator.ypp
  tools/ir-generator/irclass.cpp
Labels: core, run-ubuntu18, run-sanitizer, run-static

#4701 Configure: DOXYGEN for documentation generation
  .gitignore
  docs/doxygen/doxygen.cfg
  docs/doxygen/p4-logo.png
  docs/doxygen/p4c.css
  docs/doxygen/p4c_footer.html
  docs/doxygen/p4c_header.html
Labels: documentation

#4703 More compilation fixes for C++20: hvec_map and copy_bitref
  lib/bitvec.h
  lib/hvec_map.h
Labels: core

#4705 Update some stale DPDK error reference files.
  backends/dpdk/run-dpdk-test.py
  testdata/p4_16_dpdk_errors/pna-example-ipsec-err1.p4
  testdata/p4_16_dpdk_errors/pna-example-ipsec-err2.p4
  testdata/p4_16_dpdk_errors/pna-example-ipsec-err3.p4
  testdata/p4_16_dpdk_errors/pna-example-ipsec-err4.p4
  testdata/p4_16_pna_errors/pna-dpdk-direct-counter-err-1.p4
  testdata/p4_16_pna_errors/pna-dpdk-direct-counter-err-2.p4
  testdata/p4_16_pna_errors/pna-dpdk-direct-counter-err-3.p4
  testdata/p4_16_pna_errors/pna-dpdk-direct-counter-err-4.p4
  testdata/p4_16_pna_errors/pna-dpdk-direct-counter-err.p4
  testdata/p4_16_pna_errors/pna-dpdk-direct-meter-err-2.p4
  testdata/p4_16_pna_errors/pna-dpdk-direct-meter-err-3.p4
  testdata/p4_16_pna_errors/pna-dpdk-direct-meter-err-4.p4
  testdata/p4_16_pna_errors/pna-dpdk-direct-meter-err.p4
  testdata/p4_16_pna_errors_outputs/pna-dpdk-direct-counter-err-3.p4-error
  testdata/p4_16_pna_errors_outputs/pna-dpdk-direct-meter-err-4.p4-error
Labels: dpdk

#4182 Add P4Smith, a random program generator to the P4Tools framework
  backends/p4tools/README.md
  backends/p4tools/common/lib/util.cpp
  backends/p4tools/common/lib/util.h
  backends/p4tools/common/p4ctool.h
  backends/p4tools/modules/smith/CMakeLists.txt
  backends/p4tools/modules/smith/README.md
  backends/p4tools/modules/smith/common/declarations.cpp
  backends/p4tools/modules/smith/common/declarations.h
  backends/p4tools/modules/smith/common/expressions.cpp
  backends/p4tools/modules/smith/common/expressions.h
  backends/p4tools/modules/smith/common/generator.h
  backends/p4tools/modules/smith/common/parser.cpp
  backends/p4tools/modules/smith/common/parser.h
  backends/p4tools/modules/smith/common/probabilities.h
  backends/p4tools/modules/smith/common/scope.cpp
  backends/p4tools/modules/smith/common/scope.h
  backends/p4tools/modules/smith/common/statements.cpp
  backends/p4tools/modules/smith/common/statements.h
  backends/p4tools/modules/smith/common/table.cpp
  backends/p4tools/modules/smith/common/table.h
  backends/p4tools/modules/smith/core/target.cpp
  backends/p4tools/modules/smith/core/target.h
  backends/p4tools/modules/smith/main.cpp
  backends/p4tools/modules/smith/options.cpp
  backends/p4tools/modules/smith/options.h
  backends/p4tools/modules/smith/register.h.in
  backends/p4tools/modules/smith/scripts/compilation-test.sh
  backends/p4tools/modules/smith/smith.cpp
  backends/p4tools/modules/smith/smith.h
  backends/p4tools/modules/smith/targets/bmv2/CMakeLists.txt
  backends/p4tools/modules/smith/targets/bmv2/psa.cpp
  backends/p4tools/modules/smith/targets/bmv2/psa.h
  backends/p4tools/modules/smith/targets/bmv2/register.h
  backends/p4tools/modules/smith/targets/bmv2/target.cpp
  backends/p4tools/modules/smith/targets/bmv2/target.h
  backends/p4tools/modules/smith/targets/bmv2/test/P4Tests.cmake
  backends/p4tools/modules/smith/targets/bmv2/v1model.cpp
  backends/p4tools/modules/smith/targets/bmv2/v1model.h
  backends/p4tools/modules/smith/targets/generic/CMakeLists.txt
  backends/p4tools/modules/smith/targets/generic/register.h
  backends/p4tools/modules/smith/targets/generic/target.cpp
  backends/p4tools/modules/smith/targets/generic/target.h
  backends/p4tools/modules/smith/targets/generic/test/P4Tests.cmake
  backends/p4tools/modules/smith/targets/nic/CMakeLists.txt
  backends/p4tools/modules/smith/targets/nic/register.h
  backends/p4tools/modules/smith/targets/nic/target.cpp
  backends/p4tools/modules/smith/targets/nic/target.h
  backends/p4tools/modules/smith/targets/nic/test/P4Tests.cmake
  backends/p4tools/modules/smith/targets/tofino/CMakeLists.txt
  backends/p4tools/modules/smith/targets/tofino/register.h
  backends/p4tools/modules/smith/targets/tofino/target.cpp
  backends/p4tools/modules/smith/targets/tofino/target.h
  backends/p4tools/modules/smith/targets/tofino/test/P4Tests.cmake
  backends/p4tools/modules/smith/toolname.h
  backends/p4tools/modules/smith/util/util.cpp
  backends/p4tools/modules/smith/util/util.h
  backends/p4tools/modules/smith/util/wordlist.cpp
  backends/p4tools/modules/smith/util/wordlist.h
  backends/p4tools/modules/smith/version.h.cmake
  backends/p4tools/modules/testgen/README.md
Labels: p4tools

#4710 Add a formatter binary skeleton as P4C back end
  CMakeLists.txt
  backends/p4fmt/CMakeLists.txt
  backends/p4fmt/README.md
  backends/p4fmt/options.cpp
  backends/p4fmt/options.h
  backends/p4fmt/p4fmt.cpp
Labels: p4fmt

#4704 Format-related string fixes and refactorings
  backends/ebpf/ebpfControl.cpp
  backends/ebpf/ebpfDeparser.cpp
  backends/ebpf/ebpfParser.cpp
  backends/ebpf/ebpfTable.cpp
  backends/ebpf/psa/ebpfPipeline.cpp
  backends/ebpf/psa/ebpfPsaControl.cpp
  backends/ebpf/psa/ebpfPsaDeparser.cpp
  backends/ebpf/psa/ebpfPsaGen.h
  backends/ebpf/psa/ebpfPsaTable.cpp
  backends/ebpf/psa/externs/ebpfPsaCounter.cpp
  backends/ebpf/psa/externs/ebpfPsaDigest.cpp
  backends/ebpf/psa/externs/ebpfPsaHashAlgorithm.cpp
  backends/ebpf/psa/externs/ebpfPsaRegister.cpp
  backends/ebpf/psa/externs/ebpfPsaTableImplementation.cpp
  backends/ebpf/target.cpp
  backends/tc/ebpfCodeGen.cpp
  frontends/p4/toP4/toP4.cpp
  ir/visitor.cpp
  lib/error_reporter.h
  lib/sourceCodeBuilder.h
  lib/source_file.cpp
  lib/source_file.h
  lib/stringify.cpp
  lib/stringify.h
  test/CMakeLists.txt
  test/gtest/format_test.cpp
  test/gtest/source_file_test.cpp
  test/gtest/stringify.cpp
Labels: core, breaking-change

#4718 Invalid include fix in `p4fmt.cpp`
  backends/p4fmt/p4fmt.cpp
Labels: p4fmt

#4719 Test building P4C with `ENABLE_GTESTS=OFF` in CI
  .github/workflows/ci-test-debian.yml
  tools/ci-build.sh
Labels: test-infrastructure

#4720 Fix up the Bazel sed command.
  BUILD.bazel
Labels: test-infrastructure

#4702 Docs : Configure Doxygen and GitHub pages deploy Action
  .github/workflows/deploy-docs.yml
  docs/assets/p4-fav.svg
  docs/assets/p4-logo.png
  docs/doxygen/bfn_footer.tex
  docs/doxygen/doxygen.cfg
  docs/doxygen/p4c_header.html
Labels: documentation

#4727 Add a constant folding pass after inlining
  frontends/p4/frontend.cpp
  testdata/p4_16_samples/issue4548.p4
  testdata/p4_16_samples_outputs/gauntlet_hdr_in_value-bmv2-frontend.p4
  testdata/p4_16_samples_outputs/issue1638-frontend.p4
  testdata/p4_16_samples_outputs/issue1638-midend.p4
  testdata/p4_16_samples_outputs/issue1937-2-bmv2-frontend.p4
  testdata/p4_16_samples_outputs/issue1937-3-bmv2-frontend.p4
  testdata/p4_16_samples_outputs/issue1937-frontend.p4
  testdata/p4_16_samples_outputs/issue2303-frontend.p4
  testdata/p4_16_samples_outputs/issue2648-frontend.p4
  testdata/p4_16_samples_outputs/issue4500-frontend.p4
  testdata/p4_16_samples_outputs/issue4548-first.p4
  testdata/p4_16_samples_outputs/issue4548-frontend.p4
  testdata/p4_16_samples_outputs/issue4548-midend.p4
  testdata/p4_16_samples_outputs/issue4548.p4
  testdata/p4_16_samples_outputs/issue4548.p4-stderr
  testdata/p4_16_samples_outputs/named-arg1-frontend.p4
Labels: core

#4725 [#4006] Remove confusing warning when the same header is extracted multiple times in a parse path
  frontends/p4/coreLibrary.h
  lib/error_catalog.cpp
  lib/error_catalog.h
  midend/interpreter.cpp
  testdata/p4_16_samples/parser-unroll-issue4006_twice_extracted_header.p4
  testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header-first.p4
  testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header-frontend.p4
  testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header-midend.p4
  testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header.p4
  testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header.p4-stderr
  testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header.p4.entries.txtpb
  testdata/p4_16_samples_outputs/parser-unroll-issue4006_twice_extracted_header.p4.p4info.txtpb
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue4006_twice_extracted_header-first.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue4006_twice_extracted_header-frontend.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue4006_twice_extracted_header-midend.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue4006_twice_extracted_header.p4
  testdata/p4_16_samples_outputs/parser-unroll/parser-unroll-issue4006_twice_extracted_header.p4-stderr
Labels: core

#4735 Docs : Update community link from Slack to Zulip
  README.md
Labels: documentation

#4708 [Docs] Add initial CHANGELOG.md with changelogs from previous release
  CHANGELOG.md
  docs/doxygen/doxygen.cfg
  docs/doxygen/p4c_layout.xml
Labels: documentation

#4716 cstring-related cleanup, switch to std::string_view for some cstring API
  backends/dpdk/dpdkArch.cpp
  backends/dpdk/dpdkContext.cpp
  backends/dpdk/dpdkContext.h
  backends/ebpf/ebpfParser.cpp
  backends/ebpf/psa/ebpfPsaDeparser.cpp
  backends/ebpf/psa/ebpfPsaGen.cpp
  backends/ebpf/psa/ebpfPsaTable.cpp
  backends/ebpf/psa/externs/ebpfPsaMeter.cpp
  backends/tc/ebpfCodeGen.cpp
  lib/cstring.cpp
  lib/cstring.h
  test/gtest/cstring.cpp
  tools/ir-generator/irclass.cpp
Labels: core, breaking-change

#4741 Emit true and false instead of 1 and 0 for BoolLiteral dbprint.
  ir/dbprint-expression.cpp
Labels: core

#4737 Docs : Configuring Doxygen Awesome CSS
  .github/workflows/deploy-docs.yml
  .gitignore
  docs/assets/css/doxygen-awesome.css
  docs/doxygen/doxygen.cfg
  docs/doxygen/p4c.css
  docs/doxygen/p4c_header.html
Labels: documentation

#4749 Minor Fix: Graphs Backend Example Images
  docs/doxygen/doxygen.cfg
Labels: documentation

#4750 Fix spurious P4Testgen failure occuring because of a problem when running PTF tests in parallel.
  backends/bmv2/run-bmv2-ptf-test.py
Labels: test-infrastructure

#4722 Make sure compiler_meta__->drop starts out false
  backends/tc/ebpfCodeGen.cpp
  testdata/p4tc_samples_outputs/add_entry_1_example_control_blocks.c
  testdata/p4tc_samples_outputs/add_entry_3_example_control_blocks.c
  testdata/p4tc_samples_outputs/add_entry_example_control_blocks.c
  testdata/p4tc_samples_outputs/calculator_control_blocks.c
  testdata/p4tc_samples_outputs/checksum_control_blocks.c
  testdata/p4tc_samples_outputs/const_entries_range_mask_control_blocks.c
  testdata/p4tc_samples_outputs/default_action_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/default_action_example_control_blocks.c
  testdata/p4tc_samples_outputs/default_action_with_param_01_control_blocks.c
  testdata/p4tc_samples_outputs/default_action_with_param_control_blocks.c
  testdata/p4tc_samples_outputs/default_hit_const_example_control_blocks.c
  testdata/p4tc_samples_outputs/direct_counter_example_control_blocks.c
  testdata/p4tc_samples_outputs/drop_packet_example_control_blocks.c
  testdata/p4tc_samples_outputs/global_action_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/global_action_example_02_control_blocks.c
  testdata/p4tc_samples_outputs/hash1_control_blocks.c
  testdata/p4tc_samples_outputs/indirect_counter_01_example_control_blocks.c
  testdata/p4tc_samples_outputs/ipip_control_blocks.c
  testdata/p4tc_samples_outputs/matchtype_control_blocks.c
  testdata/p4tc_samples_outputs/mix_matchtype_example_control_blocks.c
  testdata/p4tc_samples_outputs/multiple_tables_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/multiple_tables_example_02_control_blocks.c
  testdata/p4tc_samples_outputs/name_annotation_example_control_blocks.c
  testdata/p4tc_samples_outputs/no_table_example_control_blocks.c
  testdata/p4tc_samples_outputs/noaction_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/noaction_example_02_control_blocks.c
  testdata/p4tc_samples_outputs/nummask_annotation_example_control_blocks.c
  testdata/p4tc_samples_outputs/send_to_port_example_control_blocks.c
  testdata/p4tc_samples_outputs/set_entry_timer_example_control_blocks.c
  testdata/p4tc_samples_outputs/simple_exact_example_control_blocks.c
  testdata/p4tc_samples_outputs/simple_extern_example_control_blocks.c
  testdata/p4tc_samples_outputs/simple_lpm_example_control_blocks.c
  testdata/p4tc_samples_outputs/simple_ternary_example_control_blocks.c
  testdata/p4tc_samples_outputs/size_param_example_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_02_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_03_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_04_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_05_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_06_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_07_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_08_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_09_control_blocks.c
  testdata/p4tc_samples_outputs/tc_type_annotation_example_control_blocks.c
  testdata/p4tc_samples_outputs/test_ipv6_example_control_blocks.c
Labels: p4tc, run-sanitizer

#4745 Make different Markdown files have different titles in Doxygen output
  backends/p4tools/CONTRIBUTORS.md
  backends/p4tools/cmake/README.md
  backends/p4tools/common/README.md
  backends/p4tools/common/lib/README.md
  backends/p4tools/modules/smith/README.md
  backends/p4tools/modules/testgen/README.md
  backends/p4tools/modules/testgen/lib/README.md
  backends/p4tools/modules/testgen/targets/bmv2/test/README.md
  backends/ubpf/docs/EXAMPLES.md
  backends/ubpf/tests/README.md
  ir/README.md
  lib/README.md
Labels: documentation

#4754 [P4Smith] Fix broken links in Smith README
  backends/p4tools/modules/smith/README.md
Labels: p4tools, documentation

#4755 Docs: Fixing diagram paths in generated docs
  docs/doxygen/doxygen.cfg
Labels: documentation

#4747 Docs: Add theme dependency and instructions
  .gitignore
  README.md
  docs/README.md
Labels: documentation

#4756 Add back in heading for P4Smith README file
  backends/p4tools/modules/smith/README.md
  backends/p4tools/modules/testgen/README.md
Labels: documentation

#4758 Docs: Initial sequence of pages in Documentation
  docs/doxygen/doxygen.cfg
Labels: documentation

#4761 Docs: Update compiler file structure
  docs/README.md
  docs/assets/css/doxygen-awesome.css
Labels: documentation

#4762 [#4760] Create empty `SetOfLocations` for don't care arguments passed as action `out` args
  frontends/p4/alias.h
  testdata/p4_16_samples/issue4760_dontcare_action_out_arg.p4
  testdata/p4_16_samples_outputs/issue4760_dontcare_action_out_arg-first.p4
  testdata/p4_16_samples_outputs/issue4760_dontcare_action_out_arg-frontend.p4
  testdata/p4_16_samples_outputs/issue4760_dontcare_action_out_arg-midend.p4
  testdata/p4_16_samples_outputs/issue4760_dontcare_action_out_arg.p4
  testdata/p4_16_samples_outputs/issue4760_dontcare_action_out_arg.p4-stderr
Labels: core

#4765 Fix naming of CMake Release configuration.
  .github/workflows/ci-test-fedora.yml
  .github/workflows/ci-test-mac.yml
  tools/ci-build.sh
  tools/debian-build/packaging.conf
Labels: infrastructure

#4766 Simplify dependabot label generation.
  .github/dependabot.yml
Labels: infrastructure

#4743 Add DCO description to the contribution guidelines.
  .github/dco.yml
  CONTRIBUTING.md
Labels: infrastructure
