Repository p4lang/p4c, pull requests merged in 2024-12, with the labels that each got.

#5044 Looks like PIE workaround is not needed anymore. Remove it
  CMakeLists.txt
Labels: core, run-ubuntu18, run-validation, run-sanitizer, run-static

#5043 Crude port of Tofino dynamic hash to C++
  backends/tofino/CMakeLists.txt
  backends/tofino/bf-p4c/CMakeLists.txt
  backends/tofino/bf-p4c/mau/hash_function.cpp
  backends/tofino/bf-utils/include/dynamic_hash/bfn_hash_algorithm.h
  backends/tofino/bf-utils/src/dynamic_hash/bfn_hash_algorithm.cpp
  backends/tofino/bf-utils/src/dynamic_hash/dynamic_hash.cpp
Labels: tofino

#5048 Add typed version of `isInContext()` and make use of it instead of `findContext()`
  frontends/common/resolveReferences/resolveReferences.cpp
  frontends/p4/actionsInlining.cpp
  frontends/p4/checkCoreMethods.cpp
  frontends/p4/def_use.cpp
  frontends/p4/localizeActions.cpp
  frontends/p4/moveDeclarations.cpp
  frontends/p4/moveDeclarations.h
  frontends/p4/parserControlFlow.h
  frontends/p4/redundantParsers.cpp
  frontends/p4/removeParameters.cpp
  frontends/p4/removeReturns.cpp
  frontends/p4/sideEffects.cpp
  frontends/p4/sideEffects.h
  frontends/p4/simplify.cpp
  frontends/p4/simplifyDefUse.cpp
  frontends/p4/simplifyDefUse.h
  frontends/p4/typeChecking/typeCheckDecl.cpp
  frontends/p4/typeChecking/typeCheckExpr.cpp
  frontends/p4/uniqueNames.h
  frontends/p4/unusedDeclarations.cpp
  frontends/p4/validateMatchAnnotations.h
  frontends/p4/validateParsedProgram.cpp
  ir/visitor.h
  midend/convertEnums.cpp
  midend/convertErrors.cpp
  midend/copyStructures.cpp
  midend/eliminateInvalidHeaders.cpp
  midend/eliminateSerEnums.cpp
  midend/eliminateSwitch.cpp
  midend/local_copyprop.cpp
  midend/nestedStructs.cpp
  midend/predication.cpp
  midend/removeExits.cpp
  midend/replaceSelectRange.cpp
  midend/simplifySelectList.cpp
Labels: core

#5029 Remove empty v1.def
  BUILD.bazel
  ir/v1.def
Labels: infrastructure

#5045 Docs: Changelogs for `v1.2.5.0`
  CHANGELOG.md
Labels: documentation

#5051 Fix incorrect annotation parsing in Tofino.
  backends/tofino/bf-p4c/bf-p4c-options.cpp
Labels: tofino

#5036 Fix FlattenLogMsg not properly working on nested structures
  backends/p4test/midend.cpp
  frontends/p4/toP4/toP4.cpp
  midend/flattenLogMsg.cpp
  testdata/p4_16_samples/issue5035.p4
  testdata/p4_16_samples_outputs/issue2201-bmv2-midend.p4
  testdata/p4_16_samples_outputs/issue5035-first.p4
  testdata/p4_16_samples_outputs/issue5035-frontend.p4
  testdata/p4_16_samples_outputs/issue5035-midend.p4
  testdata/p4_16_samples_outputs/issue5035.p4
  testdata/p4_16_samples_outputs/issue5035.p4-stderr
  testdata/p4_16_samples_outputs/issue5035.p4.entries.txtpb
  testdata/p4_16_samples_outputs/issue5035.p4.p4info.txtpb
Labels: core

#5039 Remove unnecessary file lists from Tofino CMake.
  .github/workflows/ci-lint.yaml
  backends/tofino/CMakeLists.txt
  backends/tofino/bf-p4c/CMakeLists.txt
  cmake/Linters.cmake
Labels: infrastructure, tofino

#5056 Add a flag to enable bf-asm for open-p4studio
  backends/tofino/bf-p4c/driver/barefoot.py
  backends/tofino/bf-p4c/driver/p4c.tofino.cfg
  backends/tofino/bf-p4c/driver/p4c.tofino2.cfg
Labels: tofino

#5052 Add checks to annotation getters.
  ir/base.def
Labels: core

#5049 Mark RTTI methods as const / pure, so compiler could optimize subsequent calls, if necessary.
  lib/rtti.h
Labels: core

#5059 Clean up Tofino dynamic hash library.
  backends/tofino/CMakeLists.txt
  backends/tofino/bf-p4c/control-plane/bfruntime_ext.h
  backends/tofino/bf-p4c/mau/hash_function.cpp
  backends/tofino/bf-p4c/mau/input_xbar.cpp
  backends/tofino/bf-p4c/mau/tofino/input_xbar.cpp
  backends/tofino/bf-p4c/midend/fold_constant_hashes.h
  backends/tofino/bf-utils/dynamic_hash/CMakeLists.txt
  backends/tofino/bf-utils/dynamic_hash/bfn_hash_algorithm.cpp
  backends/tofino/bf-utils/dynamic_hash/bfn_hash_algorithm.h
  backends/tofino/bf-utils/dynamic_hash/dynamic_hash.cpp
  backends/tofino/bf-utils/dynamic_hash/dynamic_hash.h
  backends/tofino/bf-utils/src/dynamic_hash/bfn_hash_algorithm.c
  backends/tofino/bf-utils/src/dynamic_hash/dynamic_hash.c
Labels: tofino

#5069 Fix missing indentation of bfasm-related commands.
  backends/tofino/bf-p4c/driver/barefoot.py
Labels: tofino

#5072 Remove dynhash library variable from Tofino library dependencies.
  backends/tofino/bf-p4c/CMakeLists.txt
  backends/tofino/bf-utils/dynamic_hash/CMakeLists.txt
Labels: tofino

#5071 Update to use Bazel 7.4.1.
  .bazelrc
  .bazelversion
  bazel/example/.bazelrc
  bazel/example/.bazelversion
  bazel/example/WORKSPACE.bazel
Labels: infrastructure

#5062 Remove obsolete implicit attribute `_cc_toolchain`
  bazel/p4_library.bzl
Labels: infrastructure

#5070 Add a bf-asm command line option in addition to environment variables.
  backends/tofino/bf-p4c/driver/barefoot.py
  backends/tofino/bf-p4c/driver/p4c.tofino.cfg
  backends/tofino/bf-p4c/driver/p4c.tofino2.cfg
Labels: tofino

#5075 Clean up clang-format and add a .clangd configuration.
  .clang-format
  .clangd
  test/CMakeLists.txt
  test/gtest/ir-traversal.cpp
Labels: infrastructure

#5058 Ignore typeless structs in unstructured annotations
  frontends/p4/specializeGenericTypes.cpp
Labels: core

#5079 Remove unused files from testdata
  testdata/p4_14_samples_outputs/wide_action2-midend.p4
  testdata/p4_16_dpdk_errors_outputs/pna-dpdk-large-constants.p4-error
  testdata/p4_16_dpdk_errors_outputs/pna-dpdk-large-constants.p4.bfrt.json
  testdata/p4_16_errors/constructor3_e.s
  testdata/p4_16_errors_outputs/issue-2123_e.p4.entries.txt
  testdata/p4_16_errors_outputs/issue1777-bmv2.p4.entries.txt
  testdata/p4_16_errors_outputs/issue1803_same_table_name.p4.entries.txt
  testdata/p4_16_errors_outputs/issue2283_2-bmv2.p4.entries.txt
  testdata/p4_16_errors_outputs/issue3299.p4.entries.txt
  testdata/p4_16_errors_outputs/issue532.p4.entries.txt
  testdata/p4_16_errors_outputs/table-entries-lpm-2.p4.entries.txt
  testdata/p4_16_errors_outputs/table-entries-optional-2-bmv2.p4.entries.txt
  testdata/p4_16_samples_outputs/fabric_20190420/fabric.p4.entries.txt
  testdata/p4_16_samples_outputs/omec/up4.p4.entries.txt
  testdata/p4_16_samples_outputs/pins/pins_fabric.p4.entries.txt
  testdata/p4_16_samples_outputs/pins/pins_middleblock.p4.entries.txt
  testdata/p4_16_samples_outputs/pins/pins_wbb.p4.entries.txt
  testdata/p4tc_samples_outputs/default_action_example_parser.o
Labels: infrastructure
