Repository p4lang/p4c, pull requests merged in 2025-04, with the labels that each got.

#5213 [bmv2]: support Random extern for psa/pna
  backends/bmv2/CMakeLists.txt
  backends/bmv2/common/action.cpp
  backends/bmv2/portable_common/portable.cpp
Labels: bmv2

#5216 [#5211] Run `UniqueNames` before `SimplifyParsers` pass
  frontends/p4/frontend.cpp
  frontends/p4/simplifyParsers.h
  testdata/p4_16_samples/issue5211_simplify_parsers_dup_state_local_var_decl.p4
  testdata/p4_16_samples_outputs/issue2176-bmv2.p4-stderr
  testdata/p4_16_samples_outputs/issue5211_simplify_parsers_dup_state_local_var_decl-first.p4
  testdata/p4_16_samples_outputs/issue5211_simplify_parsers_dup_state_local_var_decl-frontend.p4
  testdata/p4_16_samples_outputs/issue5211_simplify_parsers_dup_state_local_var_decl-midend.p4
  testdata/p4_16_samples_outputs/issue5211_simplify_parsers_dup_state_local_var_decl.p4
  testdata/p4_16_samples_outputs/issue5211_simplify_parsers_dup_state_local_var_decl.p4-stderr
Labels: core

#5209 Skip PSATernaryTest on Ubuntu 22.04 and add Black formatting
  backends/ebpf/tests/ptf/test.py
Labels: ebpf-psa

#5220 [Core] Fix namespace mismatch in irutils.h
  ir/irutils.h
Labels: core

#5221 [Tofino] Try to fix the dependency of mksizes in bf-asm CMake.
  backends/tofino/bf-asm/CMakeLists.txt
Labels: tofino

#5191 Replace proprietary notice and CC license on two test files with Apache-2.0
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/common/headers.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/common/util.p4
Labels: infrastructure

#5189 Remove confidential & proprietary notices from Tofino testgen test programs
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/parser_reject.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/port_metadata_unpack.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_action_declaration.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_action_profile_default.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_advance.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_cast.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_drop.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_emit_extern.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_empty.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_exit.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_extract_emit_1.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_extract_emit_2.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_extract_emit_3.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_extract_emit_4.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_extract_emit_5.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_extract_emit_6.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_extract_emit_7.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_extract_emit_8.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_hash_1.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_hash_10.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_hash_2.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_hash_3.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_hash_4.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_hash_5.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_hash_6.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_hash_7.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_hash_8.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_hash_9.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_if_stmt.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_mirror_2.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_pvs_fixed.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_random_extern.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_register_action_1.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_register_action_2.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_simple_assign_1.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_simple_assign_2.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_table_control_exact.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_table_control_lpm.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_table_control_ternary.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_table_control_ternary_anno.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_table_entries_range.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_table_no_key.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_tainted_table_key.p4
  backends/p4tools/modules/testgen/targets/tofino/test/p4-programs/tna_undefined.p4
Labels: p4tools

#5185 Try to make exename portable. Refactor searchForIncludePath.
  backends/bmv2/pna_nic/options.cpp
  backends/bmv2/portable_common/options.cpp
  backends/dpdk/main.cpp
  backends/dpdk/options.cpp
  backends/tofino/bf-asm/CMakeLists.txt
  backends/tofino/bf-asm/crash.cpp
  backends/tofino/bf-asm/exename.cpp
  backends/tofino/bf-asm/exename.h
  backends/tofino/bf-p4c/bf-p4c-options.cpp
  backends/tofino/bf-p4c/bf-p4c-options.h
  frontends/common/parser_options.cpp
  frontends/common/parser_options.h
  lib/alloc_trace.cpp
  lib/exename.cpp
  lib/exename.h
Labels: core, run-ubuntu18, run-validation, run-sanitizer, run-static, breaking-change

#5226 Fixed P4C driver utility find_bin to return on first match
  tools/driver/p4c_src/util.py
Labels: core

#5229 improve SideEffects and StrengthReduction
  frontends/p4/sideEffects.cpp
  frontends/p4/sideEffects.h
  frontends/p4/simplify.cpp
  frontends/p4/simplifyDefUse.cpp
  frontends/p4/strengthReduction.cpp
  testdata/p4_16_samples_outputs/issue1985-first.p4
  testdata/p4_16_samples_outputs/strength-first.p4
Labels: core

#5228 [bmv2] path fixes for finding BMv2
  cmake/FindBMV2.cmake
Labels: bmv2

#5233 Fix compile-time concatenation with negative right operand
  frontends/common/constantFolding.cpp
  testdata/p4_16_samples/issue5231-const-int-concat.p4
  testdata/p4_16_samples_outputs/issue5231-const-int-concat-first.p4
  testdata/p4_16_samples_outputs/issue5231-const-int-concat-frontend.p4
  testdata/p4_16_samples_outputs/issue5231-const-int-concat-midend.p4
  testdata/p4_16_samples_outputs/issue5231-const-int-concat.p4
  testdata/p4_16_samples_outputs/issue5231-const-int-concat.p4-stderr
Labels: core

#5232 Make sure Github action workflows are correctly canceled.
  .github/workflows/ci-lint.yaml
  .github/workflows/ci-ubuntu-18-nightly.yml
  .github/workflows/ci-ubuntu-22-sanitizer-nightly.yml
  .github/workflows/ci-ubuntu-p4tc-stf.yml
  .github/workflows/ci-validation-nightly.yml
  .github/workflows/deploy-docs.yml
Labels: infrastructure

#5242 Deprecate Ubuntu 18.04 CI checks.
  .github/workflows/disabled/ci-ubuntu-18-nightly.yml
Labels: infrastructure

#5241 Fix failing Fedora tests.
  backends/ebpf/runtime/ebpf_common.h
  backends/ebpf/runtime/ebpf_kernel.h
  backends/ebpf/runtime/ebpf_test.h
  tools/install_fedora_deps.sh
Labels: infrastructure
