Repository p4lang/p4c, pull requests merged in 2025-02, with the labels that each got.

#5117 Docs : Changelogs update for `v1.2.5.1` & `v1.2.5.2`
  CHANGELOG.md
Labels: documentation

#5116 Bump Doxygen `v1.13.0` -> `v1.13.2`
  .github/workflows/deploy-docs.yml
  README.md
  docs/doxygen/doxygen.cfg
  docs/doxygen/p4c_footer.html
  docs/doxygen/p4c_header.html
  docs/doxygen/p4c_layout.xml
Labels: documentation

#5128 Remove some unnecessary imports of Scapy module
  backends/bmv2/bmv2stf.py
  backends/bmv2/run-bmv2-test.py
  backends/ebpf/targets/target.py
  tools/testutils.py
Labels: infrastructure

#5132 Replace scapy pcap read write with apache 2.0 implementation in ptf
  backends/bmv2/bmv2stf.py
  backends/ebpf/targets/target.py
  backends/p4tools/modules/testgen/targets/bmv2/test_backend.cpp
  backends/p4tools/modules/testgen/targets/bmv2/test_backend.h
  requirements.txt
Labels: infrastructure

#5140 Remove old vector workarounds, slightly modernize
  ir/indexed_vector.h
  ir/vector.h
Labels: core, breaking-change

#5134 Consistently set & propagate child names
  backends/p4tools/p4tools.def
  backends/tofino/bf-p4c/ir/arch.def
  backends/tofino/bf-p4c/ir/mau.cpp
  backends/tofino/bf-p4c/ir/mau.def
  backends/tofino/bf-p4c/ir/parde-lowered.def
  backends/tofino/bf-p4c/ir/parde.def
  backends/tofino/bf-p4c/ir/tofino.def
  backends/tofino/bf-p4c/mau/asm_output.cpp
  backends/tofino/bf-p4c/parde/clot/header_validity_analysis.cpp
  backends/tofino/bf-p4c/phv/analysis/build_mutex.cpp
  frontends/p4-14/ir-v1.def
  frontends/p4/functionsInlining.cpp
  ir/base.def
  ir/expression.def
  ir/indexed_vector.h
  ir/ir-inline.h
  ir/ir.def
  ir/loop-visitor.cpp
  ir/namemap.h
  ir/node.h
  ir/nodemap.h
  ir/vector.h
  ir/visitor.cpp
  ir/visitor.h
  tools/ir-generator/methods.cpp
  tools/ir-generator/type.cpp
  tools/ir-generator/type.h
Labels: core

#5148 Bazel build: use Clang and bump rules_foreign and protobuf versions.
  .bazelrc
  WORKSPACE.bazel
  bazel/BUILD.z3.bazel
  bazel/example/.bazelrc
  bazel/example/WORKSPACE.bazel
  bazel/p4c_deps.bzl
Labels: infrastructure
