Repository p4lang/p4c, pull requests merged in 2025-01, with the labels that each got.

#5080 Bump Doxygen `v1.12.0` -> `v1.13.0`
  .github/workflows/deploy-docs.yml
  README.md
  docs/README.md
  docs/doxygen/doxygen.cfg
  docs/doxygen/p4c_footer.html
  docs/doxygen/p4c_header.html
  docs/doxygen/p4c_layout.xml
Labels: documentation

#5073 Teach functions inliner to inline into if condition
  frontends/p4/functionsInlining.cpp
  frontends/p4/functionsInlining.h
  testdata/p4_16_samples/inline-function2.p4
  testdata/p4_16_samples_outputs/inline-function2-first.p4
  testdata/p4_16_samples_outputs/inline-function2-frontend.p4
  testdata/p4_16_samples_outputs/inline-function2-midend.p4
  testdata/p4_16_samples_outputs/inline-function2.p4
  testdata/p4_16_samples_outputs/inline-function2.p4-stderr
Labels: core

#5098 lib: Add P4::warningCount() and P4::infoCount()
  lib/error.h
  test/gtest/diagnostics.cpp
Labels: core

#5102 Move all config handling into a single place – a config.h file, do not clutter the command line with these additional project-wide defines.
  BUILD.bazel
  CMakeLists.txt
  cmake/GoogleTest.cmake
  cmake/config.h.cmake
  lib/json.h
  lib/source_file.h
Labels: core

#5103 Fix class reference in Tofino 2 driver.
  backends/tofino/bf-p4c/driver/p4c.tofino2.cfg
Labels: tofino

#5097 Small fixes for p4tc
  backends/tc/ebpfCodeGen.cpp
  backends/tc/runtime/pna.h
  testdata/p4tc_samples_outputs/add_entry_1_example_control_blocks.c
  testdata/p4tc_samples_outputs/add_entry_3_example_control_blocks.c
  testdata/p4tc_samples_outputs/add_entry_example_control_blocks.c
  testdata/p4tc_samples_outputs/calculator_control_blocks.c
  testdata/p4tc_samples_outputs/checksum_control_blocks.c
  testdata/p4tc_samples_outputs/const_entries_range_mask_control_blocks.c
  testdata/p4tc_samples_outputs/default_action_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/default_action_example_control_blocks.c
  testdata/p4tc_samples_outputs/default_action_with_param_01_control_blocks.c
  testdata/p4tc_samples_outputs/default_action_with_param_control_blocks.c
  testdata/p4tc_samples_outputs/default_hit_const_example_control_blocks.c
  testdata/p4tc_samples_outputs/digest_01_control_blocks.c
  testdata/p4tc_samples_outputs/digest_control_blocks.c
  testdata/p4tc_samples_outputs/digest_parser_meta_control_blocks.c
  testdata/p4tc_samples_outputs/direct_counter_example_control_blocks.c
  testdata/p4tc_samples_outputs/direct_meter_color_control_blocks.c
  testdata/p4tc_samples_outputs/direct_meter_control_blocks.c
  testdata/p4tc_samples_outputs/drop_packet_example_control_blocks.c
  testdata/p4tc_samples_outputs/global_action_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/global_action_example_02_control_blocks.c
  testdata/p4tc_samples_outputs/hash1_control_blocks.c
  testdata/p4tc_samples_outputs/hash_control_blocks.c
  testdata/p4tc_samples_outputs/indirect_counter_01_example_control_blocks.c
  testdata/p4tc_samples_outputs/internetchecksum_01_control_blocks.c
  testdata/p4tc_samples_outputs/ipip_control_blocks.c
  testdata/p4tc_samples_outputs/is_host_port_control_blocks.c
  testdata/p4tc_samples_outputs/is_net_port_control_blocks.c
  testdata/p4tc_samples_outputs/matchtype_control_blocks.c
  testdata/p4tc_samples_outputs/meter_color_control_blocks.c
  testdata/p4tc_samples_outputs/meter_control_blocks.c
  testdata/p4tc_samples_outputs/mix_matchtype_example_control_blocks.c
  testdata/p4tc_samples_outputs/multiple_tables_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/multiple_tables_example_02_control_blocks.c
  testdata/p4tc_samples_outputs/name_annotation_example_control_blocks.c
  testdata/p4tc_samples_outputs/no_table_example_control_blocks.c
  testdata/p4tc_samples_outputs/noaction_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/noaction_example_02_control_blocks.c
  testdata/p4tc_samples_outputs/nummask_annotation_example_control_blocks.c
  testdata/p4tc_samples_outputs/send_to_port_example_control_blocks.c
  testdata/p4tc_samples_outputs/set_entry_timer_example_control_blocks.c
  testdata/p4tc_samples_outputs/simple_exact_example_control_blocks.c
  testdata/p4tc_samples_outputs/simple_extern_example_control_blocks.c
  testdata/p4tc_samples_outputs/simple_lpm_example_control_blocks.c
  testdata/p4tc_samples_outputs/simple_ternary_example_control_blocks.c
  testdata/p4tc_samples_outputs/size_param_example_control_blocks.c
  testdata/p4tc_samples_outputs/skb_meta_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_01_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_02_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_03_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_04_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_05_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_06_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_07_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_08_control_blocks.c
  testdata/p4tc_samples_outputs/tc_may_override_example_09_control_blocks.c
  testdata/p4tc_samples_outputs/tc_type_annotation_example_control_blocks.c
  testdata/p4tc_samples_outputs/test_ipv6_example_control_blocks.c
Labels: p4tc

#5109 Fix EnumeratorHandle compilation
  lib/enumerator.h
Labels: core

#5112 Remove occurrences of confidential and proprietary
  backends/p4tools/modules/smith/README.md
  backends/tofino/compiler_interfaces/LICENSE
  docs/doxygen/bfn_header.tex
Labels: documentation
